### ISSUE TITLE
Deepslate Ores generate error ,Always generate a block with ID 255

### ISSUE THREAD

**Issue by OAO-233** [Roadhog360/Et-Futurum-Requiem#411] opened 2024-01-18 18:58 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.5.1 

### Describe the Issue

Installed with Botania, and enableDeepslateOres=false.
Create a new world.
Deepslate Ores will replace for block with ID 255, and the botania block will occupy this ID.

![2024-01-19_02 22 29](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/59224525/6160f5a1-c08a-496b-8b74-f7f694308cd9)
![2024-01-19_02 24 52](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/59224525/ab62c8a5-e8f2-4388-bc39-4e301b1790e8)
↑ Screenshot taken from an environment where only EFR and Botania are installed

In addition, the situation of Thaumcraft is compared, Thaumcraft does not occupy ID255, but only copper ore spawn.
![2024-01-19_02 37 18](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/59224525/aa50541e-6e0b-4ef3-93fe-0d5a11dea7b2)

### Conflicting Mods

Botania r1.8-249

**Comment by Roadhog360** [comment] 2024-01-18 19:36
Duplicate of #341 
Unofficial 2.5.2 build is provided by TechnoParadox if you need a fix now

**Closed by Roadhog360** 2024-01-18 19:36 UTC
