### ISSUE TITLE
Incompatibility with thermal expansion mod - duplication block

### ISSUE THREAD

**Issue by Kofola45cz** [Roadhog360/Et-Futurum-Requiem#325] opened 2023-09-10 12:16 UTC
I ran into the problem of duplicating a block using another mod.
I should add that any other random blocks I tried to put in the thermal machine, the machine didn't even allow the block to be placed, e.g. vanilla dirt, gravel, etc. doesn't place the block, but only this concreat power does.
- Video with incompatibility: https://youtu.be/tmjfg-NBm7o
Main mods for duplication block:
et-futurum-requiem-2-4-6.jar
thermaldynamics-1-7-10-1-2-1-172-jar
thermalexpansion-1-7-10-4-1-5-248-jar
thermalfoundation-1-7-10-1-2-6-118-jar
thermalrecycling-1-7-10-1-1-0-5-jar

....etc. mods in modpack traincraft.cz 1.7.10 - technic

**Comment by Roadhog360** [comment] 2023-09-10 17:24
This looks like something to fix on their end, I don't think there is anything I can do about this one

**Comment by Roadhog360** [comment] 2023-09-10 17:40
Well I want to test it anyways but this video lacks any explanation as to what any of those machines are or how to use them.

**Comment by Roadhog360** [comment] 2023-09-10 18:00
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/c398fd04-2c3b-4a32-a0a9-28db06d1c674)
I tried my best to reproduce the issue anyways, looks like it's an issue where on your end the mod isn't consuming the concrete before placing it which isn't my fault. I couldn't even figure out what this thing is and could not find it in the Creative menu because you gave me no steps to reproduce, didn't list any of the blocks, what they do or how to use them. I had to scrub your video frame-by-frame to even know what some of the blocks were because you only hover over them for a few frames.

This is the best I could come up with and it does not duplicate, it consumes the concrete as expected. Either I am not reproducing the issue correctly, or your steps were missing. I am missing the one block I could not find all of the needed blocks.
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/9c35592d-4d49-4a5b-82cd-9ef7175c61b4)

I found out my "read before opening an issue" was silently unpinned without my permission or knowledge, Greg this is exactly why we enforce the template, I don't like fishing information out of users and on a different day I would have not even investigated until I got an explanation as to what I'm actually supposed to do with these blocks.

**Comment by Roadhog360** [comment] 2023-09-10 18:04
[simplescreenrecorder-2023-09-10_13.03.05.webm](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/11903511/128abbe0-01c9-483d-8d19-f4f1a0f8b211)

**Comment by Roadhog360** [comment] 2023-09-10 18:07
Also I tried to put vanilla dirt into the machine, and it worked there too and did not duplicate that either. Of course I'm still missing some things but you said it didn't even place the block. For me it did.

**Comment by GregoriusT** [comment] 2023-09-10 18:16
So the me unpinning the thing was an accident because it looked like one of those Banner messages Github puts in places, and me having the habit of closing unneeded UI elements resulted in somehow globally unpinning the issue instead of just dismissing something that looked like a global notification.

![Screenshot 2023-09-10 at 20-13-33 READ BEFORE OPENING AN ISSUE! · Issue #146 · Roadhog360_Et-Futurum-Requiem](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/4201449/a662d487-4820-4b92-bef7-a41e64084f25)

**Comment by Roadhog360** [comment] 2023-09-10 18:17
Yeah sorry, I had just edited my message to clarify it was an accident. I thought you actually meant to, mb

**Comment by Roadhog360** [comment] 2023-09-10 18:18
Still can't reproduce but I guess I'll document it for now. I should stop evaluating issues <20 minutes after waking up, it just makes me grouchy. Sorry, but I do hold true to what I said; *please use the template next time, or answer the questions within it!* Since the read before opening was unpinned I'll let this one slide even though you clearly skipped over the correct option and went to "open a blank issue" which GitHub gives me no way to remove... Argh...

That being said, Concrete code did look a little old and was due for cleanup, if you are able to reproduce the issue with this build let me know. Also as stated above, I NEED more information to proceed. I probably missed some things, there's a block I couldn't find at all that is missing. I also used the Creative versions of the devices shown since I didn't know how to give the regular ones any power.
https://github.com/Roadhog360/Et-Futurum-Requiem/suites/16011906185/artifacts/913912453

**Comment by GregoriusT** [comment] 2023-09-10 18:20
Yeah GitHub or maybe the "Refined GitHub" Browser Extension should do better with that particular UI Element.

As for the Issue itself, does the Sand Dupe Glitch with Pistons still exist in 1.7.10 without EFR? If so, it would be able to dupe Concrete and Anvils too, not to mention Thermal Expansion has Cobble Generators and ways to turn Cobble into Sand and Gravel, so you get infinite Concrete eitherways.

**Comment by Roadhog360** [comment] 2023-09-10 18:23
Yeah I figured this isn't my problem, but at the same time the concrete code did look a little stupid so I want to be sure it's the machine's fault before closing it. Any idea how to build this thing as pictured? 

> Yeah GitHub or maybe the "Refined GitHub" Browser Extension should do better with that particular UI Element.
> 
> As for the Issue itself, does the Sand Dupe Glitch with Pistons still exist in 1.7.10 without EFR? If so, it would be able to dupe Concrete and Anvils too, not to mention Thermal Expansion has Cobble Generators and ways to turn Cobble into Sand and Gravel, so you get infinite Concrete eitherways.

**Comment by Kofola45cz** [comment] 2023-09-10 20:28
Thank you for paying attention to it, I will try to find possible causes of problems myself this weekend (September 16).
It is also possible that it is a problem caused by TPS server-client.
(I was just playing on servers when I got it...)
Anyway, I'll try to duplicate it again next weekend, and if so, I'll try to find out more about what exactly is needed to duplicate it.
And I'm sorry that I didn't give enough info, unfortunately I didn't have time to do it before I left for school.

**Comment by Kofola45cz** [comment] 2023-09-16 10:34
@Roadhog360 
OK, so I found out that the duplication is first of all a server duplication, secondly it's not purely an incompatibility between thermal expasion and et futurum, it's probably a TPS bug, where the server which has a big modpack with a lot of mods, causes it to not be able to work with this without a bug....
Or it could be affecting a different mod altogether.
So I'm currently going to address this with the owner of the servers.
Unfortunately, this will be a bug that manifests itself in a certain modpack :/

And once again, I apologize for not testing it properly before submitting my report.

**Comment by Kofola45cz** [comment] 2023-09-16 10:36
I'll close for now, possibly reopen if I find out more.

**Comment by Roadhog360** [comment] 2023-09-17 02:38
Nonsense. You showed me that this issue can happen so unless I resolve it, I consider it valid for the time being.
I will need this mod pack.

**Comment by Kofola45cz** [comment] 2023-09-17 09:37
The block in the background is just a travel anchor ender io

Modpack: https://www.technicpack.net/modpack/traincraftcz-1710.892616
ut I'll tell you right away that the singleplayer in modpack won't repruduce the bug.
If so the server is forge+bukkit - Thermos
https://github.com/CyberdyneCC/Thermos/releases/download/58/libraries.zip
https://github.com/CyberdyneCC/Thermos/releases/download/58/Thermos-1.7.10-1614-server.jar
- on the server besides the mods themselves in modpack, is what I asked the owner of the server, they are mods:
modcontrol , netherportalfix , (maybe) morpheus , nomorerecipeconflict , undephangables , structpro
+ mods in modpack

Yeah, at the same time I have to mention that the other blocks I mentioned that the machine can't lay, so it's only on the server side, in singleplayer it can lay.
I know some similar glitch was in vanilla minecraft as well for duplicating vanilla tracks.
Here it's probably similar to the case that how it digs up a block quickly after laying it down, on servers with a large modpack and map.
I've also encountered the ghost glitch block, so I'm not surprised.

Anyway, that's all I can do this weekend, next weekend at most I can also try to make a local server.

**Comment by Roadhog360** [comment] 2023-09-17 09:44
Ah, Thermos is likely the issue. Thermos is unsupported because it implements Bukkit in an incredibly buggy way, it breaks or severely cripples certain game functions due to improper handling of many of its patches. I am convinced this issue can happen with other modded blocks learning this.

Before I did not know Thermos was involved. Crucible and Mohist is also unsupported but I recommend giving them a try anyways, they might fix it.

**Closed by Roadhog360** 2023-09-17 09:44 UTC
Labels: Question, Cannot Reproduce
