### ISSUE TITLE
et futurum requiem crash with thermal foundation

### ISSUE THREAD

**Issue by note-6180339** [Roadhog360/Et-Futurum-Requiem#450] opened 2024-04-09 06:05 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0_beta-1+nomixin

### Describe the Issue

Et Futurum Requiem 2.6.0 will crash with Thermal Foundation even when just using nessencery dependencies and themselves

### Conflicting Mods

Et_Futurum_Requiem-2.6.0_beta-1+nomixin
ThermalFoundation-[1.7.10]1.2.6-118

### Crash Report

https://gist.github.com/note-6180339/9834c6385df51a4c30b27619a446fe32

### Other Details

modlist:
+unimixins-all-1.7.10-0.1.17
CoFHCore-[1.7.10]3.1.4-329
Et_Futurum_Requiem-2.6.0_beta-1+nomixin
ThermalFoundation-[1.7.10]1.2.6-118

**Comment by Roadhog360** [comment] 2024-04-09 06:26
Duplicate of #449, fixed in newer commits and will be in beta 2

**Closed by Roadhog360** 2024-04-09 06:26 UTC
