### ISSUE TITLE
Game locks up when trying to load a particular world, console reaches text capacity

### ISSUE THREAD

**Issue by Zsashas** [Roadhog360/Et-Futurum-Requiem#127] opened 2022-05-24 16:39 UTC
**Starting Questions**

Version: 2.3.2
Not a crash exactly, but here's the log: https://gist.github.com/Zsashas/c40e1b5bbd4b3a5d8255e7a4411febe4
It cuts off at the end because MultiMC stopped printing after it reached the limit. I killed the client shortly after.

**Describe the bug**
The game launches fine, but whenever I try to load this particular world, this happens. The world in question is a Water World Superflat Preset but some stuff has been built there. It worked fine before switching to Requiem. The message about missing blocks is there, it's after that it locks up. The console rapidly runs out of room as it reaches text capacity very quickly.

Note: Other worlds can be opened just fine, and I even made a similar world using the same preset and that loaded too.

**To Reproduce**
1. Launch MC
2. Try to load a certain world
3. Game is loading endlessly while the console fills up to the point that MultiMC stops printing it

**Mod List**
https://gist.github.com/Zsashas/65ccd33bb029e210cb74d8372d98d323

**Comment by Roadhog360** [comment] 2022-05-24 23:20
Duplicate of #104

**Closed** 2022-06-13 01:47 UTC

**Comment by Zsashas** [comment] 2022-06-15 04:12
For anyone finding this in the future, looks like disabling the boat replacement in the config file should fix it, can be re-enabled after breaking all old boats. Worlds with no old boats in them load fine.
