### ISSUE TITLE
Backported vanilla mobs don't spawn naturally

### ISSUE THREAD

**Issue by xenoramos** [Roadhog360/Et-Futurum-Requiem#332] opened 2023-09-17 16:46 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.5.0. rc1
(but essentially it was in previous versions too, I just didn't notice it as much earlier)

### Describe the issue (IMPORTANT)
Shulkers, Husks and Strays do not spawn naturally, despite in config file it is set to "true" for all of them. Spawning them using creative mode works fine, no bugs or issues with them existing inworld.
Especially noticeable at Shulker, as there is clearly mentioned it works with HEE and even can apply HEE's "biome" color to them, but I haven't seen any in ages, but at clear installation (with and without HEE) shulkers appear pretty quickly after loading into End dimension.

### Mod list (OPTIONAL)
https://pastebin.com/xAvjLP4r

### Additional Context (OPTIONAL)
I have checked several mods individually (like DivineRPG or AoA, which add tons of mobs), I have no idea how to narrow list of potential culprits on that.
Currently I'm trying to test individual mods, but it takes tons of time

**Comment by Roadhog360** [comment] 2023-09-17 17:15
They spawn fine for me. Are you sure that you've set the Shulker spawn anywhere to true? And for husks and strays, did you check in the correct biomes on the surface?

**Comment by xenoramos** [comment] 2023-09-17 17:21
As for config - yes, I have used literally same config files to be completely sure, so on clean install shulker appear on main End island and on HEE orbs too.
As for Husks and Strays - I have seen tons of Skeletons on the snowy biome on surface at night, but not a single Stray the whole time.
And on my desert biome - had many Zombies, but not a single Husk.

**Comment by Roadhog360** [comment] 2023-09-17 17:22
Some mod is messing with my spawning code then... :/

**Comment by xenoramos** [comment] 2023-09-17 17:52
p.s. as for Shulkers, it's VERY odd. In my modpack, if I remove ONLY Hardcore Ender Expansion (while keeping everything else and having same configs), shulkers start spawning.
But if HEE and EFR are only mods - shulkers can spawn in HEE End. I guess some mod conflict with HEE and this actually breaks EFR Shulker spawn x__x

But other mobs still refuses to spawn. I guess it's unfixable multi-mod incompatibility :c

**Comment by Roadhog360** [comment] 2023-09-17 17:57
I don't declare an issue unfixable, until it is closed and marked as "Won't Fix"

Yeah some mod is making invasive changes to the spawn list. By any chance is there a mod which claims to allow the user to customize entity spawns? There might be something wrong with it. A good way to narrow down the issue is not removing one mod at a time and then adding it back, but rather, removing a handful of mods, and if the issue persists, not to add them back but keep removing batches of mods. Once a batch causes the issue to be fixed, then you slowly add mods back from that batch.

If you send me your mods and configs in a zip I'll take a look when I get a chance.

**Comment by xenoramos** [comment] 2023-09-17 18:13
I will try doing that way to determine source of the issue with overworld mobs.
And a bit later I will zip mods and configs and upload them.

**Comment by Roadhog360** [comment] 2023-09-17 18:30
EFR zombie villagers will replace the default zombie villagers on construction, the replacement is far more direct so I'm not surprised they still work.

**Comment by xenoramos** [comment] 2023-09-17 18:46
Alright... Husks (and I assume Strays, if their spawn method is similar, I just tested Husks as I found a seed where desert is close to spawn, since I have to re-make worlds after removing bunch of mods) don't spawn because of Optifine (I had literally no idea that is even theoretically possible O_O)... which is a shame, I don't have very high-end PC, so Optifine is almost a must-have for decent performance, and I don't know any alternatives for 1.7.10.
Shulkers, however, DO spawn with optifine, so there is different kind of mod conflict.

**Comment by GregoriusT** [comment] 2023-09-17 18:48
Wait you are telling me apart from messing up Block Spawn Procetion in SinglePlayer Optifine ALSO messes up the Husk and Stray Spawning Mechanic?!?!?!

**Comment by Roadhog360** [comment] 2023-09-17 19:07
I don't like the idea of telling people to just turn down their render distance and graphics, the whole point of optimization mods is so you're less likely to need to.

My solution would be trying mods like Neodymium, FastCraft, ArchaicFix and [NotFine](https://github.com/jss2a98aj/NotFine). OptiFine makes invasive changes and can occasionally break things. Here's a full list of mods that increase performance. You may have to play with some configs, and not all of them will be compatible but you're going to get better performance with different mods that OptiFine, and they'll be more compatible.

OptiFine is closed-source, makes breaking changes to the game and is severely outdated, people should really stop using it. As such, any issues that stem from OptiFine directly, are unsupported.

**Closed by Roadhog360** 2023-09-17 19:07 UTC
Labels: Mod Incompatibility

**Comment by xenoramos** [comment] 2023-09-17 19:40
Yeah, I understand about optifine related issue, but I still struggle to understand Shulker spawning issue. But I guess I'll just have to accept it.

**Comment by Roadhog360** [comment] 2023-09-17 21:54
There is probably a mod carelessly removing the Shulkers from the spawn list.

**Comment by xenoramos** [comment] 2023-09-17 22:19
I have only one mod (I'm aware of) that can do so (called BadMobs), but it has to be set up manually (to block undesired mobs, I use it for DivineRPG's merchant, since they are so annoying), but I did not add Shulker into the list. And the list does not have it.

What's more odd - if I use my full modpack with only Hardcore Ender Expansion removed, shulkers start spawn. Easy to assume "well, that means HEE does that".
But first: as far as I'm aware of, EFR is made in mind with compatibility with HEE, so it should not bug that way.
And second - if I use only EFR and HEE - shulkers still spawn. That on exact same config files. Which means it not just some certain mod alone doing that, but instead it's more like complicated multi-mod conflict, which I cannot understand ever.

**Comment by Roadhog360** [comment] 2023-09-17 22:26
I see. Interesting. If you can find the minimal reproduction mod list please open a separate issue about just the shulkers. Yes HEE is supposed to be compatible, and indeed I did extensive testing when I decided to add the bonus feature of spawning colored shulkers naturally in tweaks.

For the husk and strays issue I have decided to add back the old spawning logic as a tweak for a future update, this logic will be used by force when OptiFine is present. The old spawning logic simply added them as regular mobs instead of replacing specific sky-exposed baddies.

**Comment by xenoramos** [comment] 2023-09-17 22:52
I will try to find that minimal list, probably tomorrow or so. If I succeed in finding, I will open a new one.


And never got a chance to say huge "Thank You" for all the time and effort on the mod, EFR actually did bring me back into my modpack I've been playing for several years╰(*°▽°*)╯
