### ISSUE TITLE
Structures spawn on existing chunks

### ISSUE THREAD

**Issue by Jerome226** [Roadhog360/Et-Futurum-Requiem#131] opened 2022-06-21 23:26 UTC
**Starting Questions**
- [No idea since this is rare case bug] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

Version: Et_Futurum_Requiem-2.4.0-beta-1.jar

**Describe the bug**
I loaded my world and a fossil spawned inside my walls

**To Reproduce**
1. Load a world
2. Get lucky? and a structure spawn in existing chunks

**Mod Incompatibilities**
Since i use TerraFirmaCraftPlus, it could be a possible issue, but its still weird

**Mod List**
[modlist.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/8953351/modlist.txt)

**Screenshots**
![image](https://user-images.githubusercontent.com/55724525/174912564-6d6439f5-e8a3-454e-83df-40fe097e8158.png)

**Additional context**
None

**Comment by Roadhog360** [comment] 2022-07-02 19:28
Closing this as my question remains unanswered and it contains behavior I can't reproduce.

**Closed by Roadhog360** 2022-07-02 19:28 UTC
Labels: Cannot Reproduce, ⚠️BETA⚠️
