### ISSUE TITLE
I have a problem with the sound effects for the door, trap door, fence gates and Rain. the sound effects don't work when I open the doors and when it rains in minecraft its quiet

### ISSUE THREAD

**Issue by Belmoreworld** [Roadhog360/Et-Futurum-Requiem#253] opened 2023-03-23 04:56 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

Version: 2.4.3

### Describe the issue (IMPORTANT)

- when I place a (door/Trap door/fence gate) no sound plays when I open them. 
- When it rains in the game there is no sounds playing either. 

### Mod list (OPTIONAL)

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 23/03/23 2:39 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Jason_Vandore'/258, l='MpServer', x=1345.93, y=66.62, z=2082.29]]
	Chunk stats: MultiplayerChunkCache: 441, 450
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (938,64,1724), Chunk: (at 10,4,12 in 58,107; contains blocks 928,0,1712 to 943,255,1727), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
	Level time: 1725572 game time, 1117158 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 47 total; [EntityBat['Bat'/640, l='MpServer', x=1409.51, y=23.34, z=2101.20], EntityRabbit['Rabbit'/641, l='MpServer', x=1421.50, y=71.00, z=2150.50], EntityRabbit['Rabbit'/642, l='MpServer', x=1418.50, y=70.00, z=2150.50], EntityClientPlayerMP['Jason_Vandore'/258, l='MpServer', x=1345.93, y=66.62, z=2082.29], EntityRabbit['Rabbit'/643, l='MpServer', x=1421.50, y=71.00, z=2151.50], EntityChicken['Chicken'/535, l='MpServer', x=1309.53, y=65.00, z=2043.28], EntityBat['Bat'/536, l='MpServer', x=1313.69, y=41.10, z=2110.78], EntityPig['Pig'/538, l='MpServer', x=1308.31, y=71.00, z=2087.44], EntitySheep['Sheep'/539, l='MpServer', x=1303.09, y=64.00, z=2110.56], EntitySheep['Sheep'/540, l='MpServer', x=1310.56, y=64.00, z=2115.47], EntitySheep['Sheep'/541, l='MpServer', x=1311.50, y=64.00, z=2112.50], EntityTrail['unknown'/2212, l='MpServer', x=1345.93, y=66.62, z=2082.29], EntityChicken['Chicken'/552, l='MpServer', x=1324.16, y=65.00, z=2049.66], EntityCovenWitch['Coven Witch'/553, l='MpServer', x=1321.16, y=66.00, z=2054.50], EntityPig['Pig'/554, l='MpServer', x=1324.31, y=64.00, z=2048.53], EntityBat['Bat'/555, l='MpServer', x=1326.75, y=26.10, z=2078.25], EntitySheep['Sheep'/556, l='MpServer', x=1318.56, y=67.00, z=2115.34], EntitySheep['Sheep'/557, l='MpServer', x=1312.91, y=64.00, z=2119.09], EntitySheep['Sheep'/558, l='MpServer', x=1322.66, y=65.00, z=2124.50], EntitySheep['Sheep'/559, l='MpServer', x=1319.28, y=63.00, z=2105.22], EntitySheep['Sheep'/560, l='MpServer', x=1319.78, y=63.00, z=2133.81], EntityPig['Pig'/568, l='MpServer', x=1338.34, y=62.39, z=2041.50], EntityPig['Pig'/569, l='MpServer', x=1338.88, y=63.00, z=2051.22], EntityPig['Pig'/570, l='MpServer', x=1334.50, y=64.00, z=2064.50], EntityBat['Bat'/573, l='MpServer', x=1354.75, y=18.10, z=2026.25], EntityMinecartChest['entity.MinecartChest.name'/574, l='MpServer', x=1347.50, y=20.50, z=2122.50], EntityPig['Pig'/575, l='MpServer', x=1342.31, y=65.00, z=2128.56], EntityItemFrame['entity.ItemFrame.name'/450, l='MpServer', x=1215.50, y=63.50, z=2066.94], EntityItemFrame['entity.ItemFrame.name'/451, l='MpServer', x=1215.50, y=64.50, z=2066.94], EntitySturgeon['Sturgeon'/582, l='MpServer', x=1386.69, y=60.99, z=2011.56], EntityBasicFish['Fish'/585, l='MpServer', x=1376.80, y=61.52, z=2049.55], EntityChicken['Chicken'/586, l='MpServer', x=1364.56, y=62.48, z=2055.56], EntityMinecartChest['entity.MinecartChest.name'/587, l='MpServer', x=1365.50, y=22.34, z=2082.50], EntityPig['Pig'/603, l='MpServer', x=1380.50, y=63.00, z=2067.81], EntityChicken['Chicken'/604, l='MpServer', x=1391.50, y=66.00, z=2078.50], EntityChicken['Chicken'/605, l='MpServer', x=1385.41, y=66.00, z=2072.34], EntityChicken['Chicken'/606, l='MpServer', x=1388.50, y=68.00, z=2080.50], EntityChicken['Chicken'/607, l='MpServer', x=1391.72, y=67.00, z=2080.63], EntityItemFrame['entity.ItemFrame.name'/488, l='MpServer', x=1216.50, y=63.50, z=2066.94], EntityBat['Bat'/623, l='MpServer', x=1397.41, y=50.03, z=2011.47], EntityCow['Cow'/625, l='MpServer', x=1407.66, y=69.00, z=2026.84], EntityCow['Cow'/626, l='MpServer', x=1407.50, y=65.00, z=2037.72], EntityShot['entity.KoadPirates.Shot.name'/2290, l='MpServer', x=1341.05, y=65.01, z=2074.82], EntityBat['Bat'/627, l='MpServer', x=1398.47, y=18.00, z=2035.69], EntityBat['Bat'/628, l='MpServer', x=1395.22, y=49.57, z=2081.53], EntityCow['Cow'/638, l='MpServer', x=1408.31, y=72.00, z=2028.41], EntityCow['Cow'/639, l='MpServer', x=1411.25, y=65.00, z=2031.53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1719656344 bytes (1639 MB) / 4127195136 bytes (3936 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHIJAAAA	legendarium{4.1} [Legendary Item] ([1.7.10]+Legendary+Item+v4.1.jar) 
	UCHIJAAAA	fusionutil{0.1} [FusionUtil] ([1.7.10]FusionUtil-0.1.0.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-Mod-1.7.10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-399.jar) 
	UCHIJAAAA	asielib{0.2.7} [asielib] (AsieLib-1.7.10.zip) 
	UCHIJAAAA	betterbuilderswands{0.6.1} [Better Builder's Wands] (Better-Builders-Wands-Mod-1.7.10.jar) 
	UCHIJAAAA	betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJAAAA	campfirebackport{1.7.10-1.10} [Campfire Backport] (campfirebackport-1.7.10-1.10.jar) 
	UCHIJAAAA	CarpentersBlocks{3.2.5} [Carpenter's Blocks] (Carpenters-Blocks-Mod-1.7.10.zip) 
	UCHIJAAAA	lotr{Update v36.15 for Minecraft 1.7.10} [The Lord of the Rings Mod] (LOTRMod+v36.15.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (Twilight-Forest-Mod-1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.347} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.6.4} [CustomNPC+] (CustomNPC-Plus-1.6.4.jar) 
	UCHIJAAAA	DisenchanterMod{1.6} [Disenchanter] (DisenchanterMod-[1.7.10]1.6.jar) 
	UCHIJAAAA	dmod{1.0.3.4} [D-Mod] (DMod-1.7.10-1.0.3.4.jar) 
	UCHIJAAAA	dungeontools{2.0} [Dungeon Tools] (dungeontools-2.0_1.7.10.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion++MC-1.7.10++v1.8.6.jar) 
	UCHIJAAAA	etfuturum{2.4.3} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.4.3.jar) 
	UCHIJAAAA	evilnotchlib{1.0} [Evil Notch Lib] (evilnotchlib-a109.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	UCHIJAAAA	fantastic{1.0.0} [Fantastic Fish] (fantastic-1.4.jar) 
	UCHIJAAAA	ftfloocraft{1.7.10-1.7} [Floocraft] (Floocraft-1.7.10-1.7.jar) 
	UCHIJAAAA	FoodPlus{3.2rS} [§bFood Plus] (Food-Plus-Mod-1.7.10.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJAAAA	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar) 
	UCHIJAAAA	FpsReducer{mc1.7.10-1.10.3} [FPS Reducer] (FpsReducer-mc1.7.10-1.10.3.jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	headcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-Mod-1.7.10.jar) 
	UCHIJAAAA	astikoor{1.0.0} [Astikoor] (Horse-Carts-Mod-1.7.10.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-fairplay.jar) 
	UCHIJAAAA	locks{1.0.0} [Locks] (Locks-1.0.0.jar) 
	UCHIJAAAA	lootplusplus{0.24_for_1.7} [Loot++] (Loot++-0.24_for_1.7.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	mineTunes{1.1-5} [mineTunes] (MineTunes+1.1-5.jar) 
	UCHIJAAAA	MovingWorld{1.7.10-1.8.1} [Moving World] (movingworld-1.7.10-1.8.1.jar) 
	UCHIJAAAA	netherite{1.2} [Netherite 1.7.10] (netherite-1.2+1.7.10.jar) 
	UCHIJAAAA	StellarAPI{0.1.3.8} [Stellar API] (Stellar+API-0.1.3.8.jar) 
	UCHIJAAAA	Photoptics{0.1.1.8.2} [Photoptics] (Photoptics-0.1.1.8.2.jar) 
	UCHIJAAAA	KoadPirates{For minecraft 1.7.2} [Koadmaster's Pirates] (Pirates-Mod-1.7.10.jar) 
	UCHIJAAAA	libsandstone{1.0.0} [libsandstone] (Reliquary-1.7.10-1.2.1.483.jar) 
	UCHIJAAAA	xreliquary{1.2} [Reliquary] (Reliquary-1.7.10-1.2.1.483.jar) 
	UCHIJAAAA	corerm{1.0c} [RikMuld's Core] (RikMulds-Core-1.7.10.jar) 
	UCHIJAAAA	signpost{1.08.4} [Signpost] (signpost-1.7.10-1.08.4.jar) 
	UCHIJAAAA	silkspawnersdev{1.1} [silkspawners] (silkspawners-core-1.1.jar) 
	UCHIJAAAA	StorageDrawers{1.7.10-1.10.9} [Storage Drawers] (StorageDrawers-1.7.10-1.10.9.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build991} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.build991.jar) 
	UCHIJAAAA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (Tinkers-Mechworks-Mod-1.7.10.jar) 
	UCHIJAAAA	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	UCHIJAAAA	uncrafted{2.2.0} [Uncrafted Mod] (Uncrafted+1.7.10+(v.2.2.0).jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (Witchery-Mod-1.7.10.jar) 
	UCHIJAAAA	wolfarmor{1.3.0} [Wolf Armor and Storage] (Wolf-Armor-Storage-Mod-1.7.10.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.347} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	McMultipart{1.2.0.347} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (NetherPortalFix-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.78' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.78, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

### Additional Context (OPTIONAL)

I think it may have something to do with the lord of the rings mod I have in the pack. which I think may effect the sound? I am not sure. I will also add the version of the lord of the rings mod.

LOTRMod+v36.15

**Comment by Belmoreworld** [comment] 2023-03-23 14:37
Uh where would I locate these files? I am still a bit new to finding certain files in Minecraft.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Belmoreworld** [comment] 2023-03-23 22:15
Is this what you mean?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Roadhog360** [comment] 2023-03-23 22:17
Is... What?
If there is supposed to be a file attached it's not there.

**Comment by Belmoreworld** [comment] 2023-03-23 22:34
I did send a flie but I will try again just give me a second

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Belmoreworld** [comment] 2023-03-23 22:36
I will be sending the file now and if that doesn’t show I’ll just copy and paste the text of the log.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Roadhog360** [comment] 2023-03-23 22:37
I don't see it anywhere. But as a side note you should use websites like pastebin, instead of dumping the entire log in a comment.

**Comment by Belmoreworld** [comment] 2023-03-23 22:42
Alright, I will set up a pastebin account, I will take your advice and use it.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Belmoreworld** [comment] 2023-03-23 22:51
Also pastebin has a limit on how much to send. What should be pasted in stead? Because I can not send the whole thing on pastebin. And the pastbin pro is sold out.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Roadhog360** [comment] 2023-03-23 22:57
Oh, just split it I guess. How come you can't just go on the website and send it here?

**Comment by Belmoreworld** [comment] 2023-03-23 22:59
I am new to all of this as I have stated before. I have never used paste bin since it is a new website that I didn’t know it existed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Roadhog360** [comment] 2023-03-23 23:00
I meant sending it on GitHub, instead of replying through email.

It should allow you to send it with no problem even if it's quite large.

**Comment by Belmoreworld** [comment] 2023-03-23 23:03
[2023-03-24-1.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/11057070/2023-03-24-1.log)

**Comment by Belmoreworld** [comment] 2023-03-23 23:03
did that work?

**Comment by Roadhog360** [comment] 2023-03-23 23:04
Yes, I'll take a look. Thank you

**Comment by Belmoreworld** [comment] 2023-03-23 23:06
alright, cool. Thank you for helping me out by the way.

**Comment by GregoriusT** [comment] 2023-03-24 01:50
Just listing all the missing Sounds

[00:26:20] [Client thread/WARN]: File minecraft_1.18:sounds/ambient/cave/cave14.ogg does not exist, cannot add it to event etfuturum:ambient.cave
[00:26:20] [Client thread/WARN]: File minecraft_1.18:sounds/ambient/cave/cave15.ogg does not exist, cannot add it to event etfuturum:ambient.cave
[00:26:20] [Client thread/WARN]: File minecraft_1.18:sounds/ambient/cave/cave16.ogg does not exist, cannot add it to event etfuturum:ambient.cave
[00:26:20] [Client thread/WARN]: File minecraft_1.18:sounds/ambient/cave/cave17.ogg does not exist, cannot add it to event etfuturum:ambient.cave
[00:26:20] [Client thread/WARN]: File minecraft_1.18:sounds/ambient/cave/cave18.ogg does not exist, cannot add it to event etfuturum:ambient.cave
[00:26:20] [Client thread/WARN]: File minecraft_1.18:sounds/ambient/cave/cave19.ogg does not exist, cannot add it to event etfuturum:ambient.cave
[00:28:48] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft_1.18:block.wooden_door.open
[00:28:49] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft_1.18:block.wooden_door.close
[00:31:51] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft_1.18:item.crop.plant
[00:39:27] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft_1.18:block.barrel.open
[00:39:27] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft_1.18:block.barrel.close
[00:47:31] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft:mob.witch.hurt

Also this is probably the cause:


[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.io.IOException: Server returned HTTP response code: 400 for URL: http://resources.download.minecraft.net/43/438ca03b7388044ed19264a3813cf9cc992df4d5
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(Native Method)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.security.AccessController.doPrivileged(AccessController.java:713)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1489)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ganymedes01.etfuturum.repackage.makamys.mclib.ext.assetdirector.AssetFetcher.copyURLToFile(AssetFetcher.java:176)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ganymedes01.etfuturum.repackage.makamys.mclib.ext.assetdirector.AssetFetcher.downloadAsset(AssetFetcher.java:110)
[00:25:22] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at ganymedes01.etfuturum.repackage.makamys.mclib.ext.assetdirector.AssetFetcher.fetchAsset(AssetFetcher.java:74)

**Comment by Roadhog360** [comment] 2023-03-24 03:08
Yeah, Java 1.8.0_51 has trouble with this. This will be fixed in 2.4.4.

For now if you download and install Minecraft 1.18 from the launcher, the issue should be worked around for the time being.

**Closed by Roadhog360** 2023-03-24 03:08 UTC
