### ISSUE TITLE
Grass Path walking errors

### ISSUE THREAD

**Issue by AstroTibs** [Roadhog360/Et-Futurum-Requiem#51] opened 2021-06-15 17:05 UTC
The player is unable to step off of grass path onto stair blocks, or (critically) through village doorways.

I understand that this was an issue originally when grass paths were introduced, but it was eventually fixed by Mojang and later by UpToDateMod.

**Comment by Roadhog360** [comment] 2021-06-18 04:46
It was fixed by UpToDate because he changed it to a full hitbox.

**Comment by Roadhog360** [comment] 2021-06-18 04:46
I don't know why GitHub keeps randomly closing issues I comment on when I click "Comment" and not "Close with Comment"

**Comment by GregoriusT** [comment] 2021-06-19 22:04
Is the partial Hitbox like Soulsand required for the Path Blocks functionality? It could have a full Collision Box and still keep the partial Render, Selection and Hit Box. (Yeah there is 4 different Boxes to take care of...)

**Comment by Roadhog360** [comment] 2021-06-19 22:09
Yes but it should be configurable as full hitbox is not vanilla.

**Comment by GregoriusT** [comment] 2021-06-19 23:15
Full Collision for Paths = Vanilla
All other Boxes are partial Boxes like Soulsand.

No need to make anything different from how Vanilla does it at all. You can specify all 4 Boxes individually.

**Comment by Roadhog360** [comment] 2021-06-21 01:36
https://user-images.githubusercontent.com/11903511/122695828-8b661e80-d20f-11eb-8a43-699e5a86e6b4.mp4

Full collision != Vanilla

**Comment by GregoriusT** [comment] 2021-06-21 02:25
Wait then how did they fix the Path to Stair Transition? Because that is supposedly actually working. ?

**Comment by DarianLStephens** [comment] 2021-06-21 03:20
Maybe they upped the maximum 'step' distance?
Potentially easy way to test: Go in to the game, place a slab, then carpet on top of the block in front of it.
Since the carpet would make it slightly higher than half a block (Because it actually has collision in newer versions), you should be able to step up it.
You could do a similar experiment in 1.7 with snow. Snow's collision is one layer smaller than its actual box, like Soul Sand, so I think you'd need to place two to match carpet.

**Comment by Roadhog360** [comment] 2021-06-21 03:26
In modern the maximum step distance is higher, and the issue where you cannot step into a two block gap is fixed.

**Comment by DarianLStephens** [comment] 2021-06-21 07:16
Yeah, but in 1.7, carpets don't have a collision box.
Or, at least, it doesn't match the visuals, being sunk in to the ground below it.

**Comment by GregoriusT** [comment] 2021-06-21 08:05
Ah yeah, there definitely must be someway to increase the Step Height, I saw some Modular Armor and Improved Player Movement Mods do that, just dont remember what their Names were. Should be easy to find though once I am not melting in the heat anymore..

**Comment by Roadhog360** [comment] 2021-06-21 18:48
It's not all just step height though, you can definitely step from grass or soul sand, etc into a two block gap but in 1.7 you just... can't. There's another stepping bug where you can't step if there's a block right above your head.

**Comment by DarianLStephens** [comment] 2021-06-22 05:39
Maybe it wrongly assumes the player is stepping up a full half-block when it tries to climb?
That is a complete shot in the dark.

**Comment by Roadhog360** [comment] 2021-07-09 02:06
Temporary solution added by making it so grass paths have an option to be a full block in 2.2.0

**Comment by makamys** [comment] 2021-09-08 13:02
Changing the step height is as easy as changing the value of `Entity#stepHeight`, I can confirm setting it to 0.6 fixes this issue.
> 
> 
> you are supposed to be able to step from grass or soul sand, etc into a two block gap but in 1.7 you just... can't. There's another stepping bug where you can't step if there's a block right above your head, it wrongly declares the opening as something you can't fit into.

I can't understand what you mean by these, can you post visuals?

**Comment by Roadhog360** [comment] 2021-09-08 17:16
S = Path or soul sand
B = full block
P = You

  B

Y
SB

You are on the soul sand. You cannot go right.

**Comment by makamys** [comment] 2021-09-08 17:51
I see, you're right. For whatever reason, this only happens with entities with a bounding box is taller than 1.5625 units. The player is 1.8 units tall. Of course, reducing this wouldn't be an acceptable workaround - it's 1.8 units in newer versions too.

**Comment by makamys** [comment] 2021-09-08 18:23
Turns out the way stepping up is implemented in 1.7.10 is first the entity is slid `stepHeight` units up, then the X and Z motion is applied, then the entity is slid `stepHeight` units back down as far as possible. It's no wonder your issue happens.
Personally I would consider fixing this to be outside the scope of Et Futurum (if it's even possible to fix without breaking everything), and something better suited for a bug fix mod like Bugtorch.

**Closed** 2022-06-23 23:56 UTC
Labels: Temporary Fix Made

**Comment by makamys** [comment] 2022-06-24 09:22
You can step into a two block high gap now, but path->stair transitions still don't work (tested with 334ecf8).

https://user-images.githubusercontent.com/13667520/175504971-845759d4-9dab-4751-ac04-b2120f894f5e.mp4

.

**Comment by makamys** [comment] 2022-07-07 09:57
I can confirm stepping up to slabs works correctly as of 50ef279 - the issue is now fully fixed.
