### ISSUE TITLE
Crazycraft (with a few fps mods) 3.0.2 Crashing

### ISSUE THREAD

**Issue by Parrottitan** [Roadhog360/Et-Futurum-Requiem#300] opened 2023-08-13 19:19 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.4.6

### Describe the issue (IMPORTANT)

So what you need to do is you need to get https://www.curseforge.com/minecraft/modpacks/betterfpsboost/files/3811092 and install that. Then to get crazycraft 3.0.2 which can be gotten through the voidswrath launcher or what I did is I got an archive from archive.org of the server version and got all of the mods and configs and put it into my launcher of choice. (prism launcher) It launched fine and I then put et futurum requiem and it crashes. https://pastebin.com/vDFMEdth

**Comment by GregoriusT** [comment] 2023-08-13 19:32
The most obvious looking Error is the following one

```
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
```

**Comment by Parrottitan** [comment] 2023-08-13 19:35
No, it works fine when I dont have et futurum requiem, it is just et futurum requiem that makes it crash.

**Comment by GregoriusT** [comment] 2023-08-13 20:02
Oh that wasn't a message for you, that was a message pointing roadhog to the probable issue, since there is a LOT of error messages in this. ;)

**Comment by Parrottitan** [comment] 2023-08-13 20:04
My bad sorry.

**Comment by Roadhog360** [comment] 2023-08-13 21:43
There is a mod loading EntityClientPlayerMP into the classpath too early.

**Comment by Roadhog360** [comment] 2023-08-15 00:32
Would you be willing to help me pin it down to a specific mod in your instance by removing mods until the crash goes away?

**Comment by Parrottitan** [comment] 2023-08-15 01:08
Yes, I can update you tomorrow on which mod it is because right now it is night for me.

**Comment by Parrottitan** [comment] 2023-08-15 17:47
Hello! I have found the mod that causes the issues, it is https://www.curseforge.com/minecraft/mc-mods/malisiscore which I used for the mod https://www.curseforge.com/minecraft/mc-mods/malisisdoors.

**Comment by Roadhog360** [comment] 2023-08-22 17:14
What happens if you disable the mix in for hurt sounds? Furhermore, what happens if you install mixingasm or alternatively, unimixin and install the nomixin version of EFR?

**Comment by Roadhog360** [comment] 2023-08-25 17:18
@Parrottitan

**Comment by Roadhog360** [comment] 2023-08-25 17:33
Tried to reproduce this in four cases, all with [malisiscore](https://www.curseforge.com/minecraft/mc-mods/malisiscore):
[UniMixin](https://www.curseforge.com/minecraft/mc-mods/unimixins/download/4600285) with EFR 2.4.6+nomixin
EFR 2.4.6 regular, no unimixin
[UniMixin](https://www.curseforge.com/minecraft/mc-mods/unimixins/download/4600285) with EFR SNAPSHOT 10c8458+nomixin
EFR 2.4.6 10c8458, no unimixin

All four cases worked and I could load into a world, I cannot reproduce this conflict.

**Comment by Parrottitan** [comment] 2023-08-25 17:59
How odd, I will try to experiment to see why you can't get it to work. Will update you if I get anything. (sorry about not noticing your responses, was busy with stuff)

**Comment by Roadhog360** [comment] 2023-08-25 18:31
Did you change any of the config files

**Comment by Roadhog360** [comment] 2023-09-01 02:37
Any updates?

**Comment by Parrottitan** [comment] 2023-09-01 12:18
Sorry have been busy with schoolwork and haven't gotten the chance to experiment that much, will update you if there is anything else.

**Comment by Parrottitan** [comment] 2023-09-05 22:22
Been messing around with it a lot but still can't figure it out, oh well.

**Comment by Roadhog360** [comment] 2023-09-05 23:51
Are you no longer able to reproduce the issue?

**Comment by Parrottitan** [comment] 2023-09-06 00:09
I can't reproduce the issue with configuring and trying with a bunch of different mods, it is very odd.

**Comment by Roadhog360** [comment] 2023-09-06 02:42
If you consider this solved you can close this and re open if you end up running into issues again.

**Closed** 2023-09-06 10:47 UTC
Labels: Cannot Reproduce
