### ISSUE TITLE
Otherside and Pigstep not playing.

### ISSUE THREAD

**Issue by happyburger23** [Roadhog360/Et-Futurum-Requiem#340] opened 2023-09-28 00:13 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
Et_Futurum_Requiem-2.5.1

### Describe the issue (IMPORTANT)
Otherside and Pigstep do not produce sound, despite the "Jukebox/Noteblocks" slider being at 100% volume. My computer's volume is also working fine.

### Additional Context (OPTIONAL)
<img width="640" alt="Screenshot 2023-09-27 at 7 58 29 PM" src="https://github.com/Roadhog360/Et-Futurum-Requiem/assets/93412223/26b30244-b92d-497a-96c1-6d23efe9bced">

**Comment by Roadhog360** [comment] 2023-09-28 00:19
Works for me. Do other sounds from mod blocks play?

**Comment by happyburger23** [comment] 2023-09-28 00:46
Tuff, Deepslate (and the deepslate ores), Red Nether Bricks, all Nether Brick variants, Bone Blocks, Sponge, Wet Sponge, Ancient Debris, Netherwart Blocks, Nether Gold, Netherite Blocks, etc.

I think every other block with the new sounds is affected. Blocks that use the 1.7 sounds (banners, smokers, blast furnaces etc.) are unaffected

**Comment by Roadhog360** [comment] 2023-09-28 00:48
Post a full log. This sounds like it might be a duplicate of #293

**Comment by happyburger23** [comment] 2023-09-28 00:49
[latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/12744335/latest.log)

**Comment by Roadhog360** [comment] 2023-09-28 00:52
You're using a really weird version of Java which is probably causing this issue. Update your Java to a newer Java 8 version such as Java 8 361.

You're on Java 8 71. The patch for this issue is only for Java 8 51 because the vanilla and Curse laucnhers ship with it, since you're supplying a custom Java version I'd highly recommend updating to the latest build of Java 8.

**Closed by Roadhog360** 2023-09-28 00:52 UTC
Labels: Cannot Reproduce

**Comment by Roadhog360** [comment] 2023-09-28 00:59
Feel free to comment here if either of these work for you. I also forgot that you can manually install the resources by just downloading 1.20.2
