### ISSUE TITLE
Strange dropping of items in my mod packs

### ISSUE THREAD

**Issue by 167OSS** [Roadhog360/Et-Futurum-Requiem#473] opened 2024-06-01 08:30 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.0

### Describe the Issue

https://github.com/Roadhog360/Et-Futurum-Requiem/assets/78334210/7d03daea-4297-40fa-8297-3dcbeb2b36d5

### Conflicting Mods

Not yet identified

### Crash Report

NO

### Other Details

[lme_export.json](https://github.com/user-attachments/files/15521055/lme_export.json)
[latest.log](https://github.com/user-attachments/files/15521056/latest.log)

**Comment by Roadhog360** [comment] 2024-06-01 08:57
Duplicate of #448
Update ArchaicFix, it is outdated

**Closed** 2024-06-01 08:57 UTC

**Comment by Roadhog360** [comment] 2024-06-01 17:05
Also next time log file should be put in a paste website, not uploaded directly. I can't preview them without downloading it
