### ISSUE TITLE
The Raw Thorium From this mod doesn't have all recipes that the Thorium ore From HBM's NTM has.

### ISSUE THREAD

**Issue by Millymilo000** [Roadhog360/Et-Futurum-Requiem#528] opened 2024-10-08 02:57 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.6.0.jar

### Describe the Issue

The Raw thorium that is created by this mod, is missing some of the recipes that the Thorium ore from [HBM's Nuclear Tech mod](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT)

The recipes raw thorium is missing are: Use in Centrifuge, Use in Acidizer, Use in Crucible, and Use in Arc Furnace (Fluid).

### Other Details

I believe that this is due to the raw thorium created by this mod, isn't in the ore dictionary "oreThorium232" which HBM's Nuclear Tech Mod uses ores in that dictionary for the recipe in those crafting stations.

**Comment by Roadhog360** [comment] 2024-10-08 02:59
Why is it not just `oreThorium`? This doesn't seem to match the conventions that OreDictionary ores typically follow...

**Comment by Millymilo000** [comment] 2024-10-08 03:02
No clue, taking a look in the HBMRecipes default config file, it uses "oreThorium232" for those recipes, despite the thorium ore already having "oreThorium" OreDictionary.

My guess it's just something that was put there years ago and never thought about updating, since HBM's nuclear tech mod is so old.

**Comment by GregoriusT** [comment] 2024-10-08 03:41
The Issue is Bob does not always use OreDict in his Machines lol

**Comment by Millymilo000** [comment] 2024-10-08 04:03
> The Issue is Bob does not always use OreDict in his Machines lol

I don't know about the ore acidizer since it doesn't seem to have a recipe config file, but I checked the other machine's recipe config file and they all use the `oreThorium232` OreDict for thorium. I still see how that is could be an issue for other ores not from this mod though.

**Comment by Roadhog360** [comment] 2024-10-08 05:57
There isn't much I should be expected to do on my end, mods should be using the OreDictionary lol

**Comment by GregoriusT** [comment] 2024-10-08 07:05
yeah this is either a bob issue or its bob specifically requiring a specific thorium isotope and not just some random oreThorium. in any case, thats indeed a thing for bob to decide.

**Comment by HbmMods** [comment] 2024-10-08 07:53
> Why is it not just `oreThorium`

Because it's an isotope

> This doesn't seem to match the conventions that OreDictionary ores typically follow

It does, for isotopes

> despite the thorium ore already having "oreThorium" OreDictionary

Something that I shouldn't even have done in the first place, I do believe mixing isotope keys and generic element keys is a bad idea. If anything, the ore should only be `oreThorium232` because that's what the ore yields.

> I don't know about the ore acidizer since it doesn't seem to have a recipe config file

`hbmCrystalliser.json` in `hbmRecipes`

> clearly established coventions

Speaking of, what even *are* the conventions? Because as far as I can tell, nobody seems to agree on how the OD should even be used, save for the prefix+material format, and I don't recall Forge ever releasing some sort of official specifications.

**Comment by Roadhog360** [comment] 2024-10-08 08:20
oreMaterial, never a number of some sort after it. Wouldn't other metals have some sort of isotope number after them? Why didn't copper or gold get it? Why is Thorium such a specific case here?

**Comment by HbmMods** [comment] 2024-10-08 09:06
The ore, ingot, nugget and everything else use `Thorium` as well as `Thorium232`, the former only for compatibility purposes, it's just that the recipe gen for the ore only checks for the latter.

> Why is Thorium such a specific case here?

Because ever since IC2 decided that U238 should be "Uranium" and U235 should be "Uranium235", isotope ore dict keys have always been a complete clusterfuck and defaulting Thorium to 232 was the only reasonable way I could think of without making a separate material.

**Comment by GregoriusT** [comment] 2024-10-08 15:51
The number after the Ore to indicate Isotope is actually part of the name of the Material itself. So that Thorium is a different Thorium from the Thorium Ore you have.

And yes the Nuclear OreDict Names are a wee bit unclear in some aspects.

Roadhog, I dont think you should try anything about this, this is the stuff for Bob (and often also me) to worry about. ;)

**Comment by Roadhog360** [comment] 2024-10-08 15:53
I'm unsure if I should try or just leave it be. I have no idea what this isotope stuff means admittedly so I trust you Greg whether to leave it open or close this issue.

**Comment by GregoriusT** [comment] 2024-10-08 17:49
Yeah, in case of Bob it might screw up balance. It is bad enough that my GT6 Bismuth Ore is bypassing most of his progression somehow. xD

**Closed by GregoriusT** 2024-10-08 17:49 UTC

**Comment by HbmMods** [comment] 2024-10-08 18:19
> this is the stuff for Bob (and often also me) to worry about. ;)

I extended recipe autogen to all material suffixes of the ore (`Thorium`, `Thorium233` as well as `Th232` because NuclearCraft, yay) which should make all Thorium ores interchangeable. Balancing-wise this will only have implications when something is installed that treats `oreThorium` as consisting of Th230 and Th232, which I'm not even sure GT does so we're probably in the clear here.

> It is bad enough that my GT6 Bismuth Ore is bypassing most of his progression somehow

Yeah originally I omitted oredicting for Bismuth entirely because of that, but then added it anyway because having to deal with the entirety of GT6 sounds like a fair tradeoff to having Bismuth be available early on.
