### ISSUE TITLE
Door Sound Bug

### ISSUE THREAD

**Issue by unabletofindname** [Roadhog360/Et-Futurum-Requiem#296] opened 2023-08-02 19:38 UTC
Bug Report:

Doors and some other blocks have no sound when this mod is installed. Including vanilla doors.

**Comment by GregoriusT** [comment] 2023-08-02 20:17
@Roadhog360  you need to consider actually having a Fallback for this type of stuff, there is situations where it is better to fail only for new sounds as opposed to removing all the modified sounds, just because someone either does not have Internet or lives in a country that is not supported by Microsoft.

I can see this Issue becoming one of the recurring time wasters for not just you but also the end users, because people will think of this as a bug and not "a config you can turn off".

And again I do not talk about including the sound files in the jar, i'm talking about just the already existing sounds not being redirected to empty locations.

Maybe there should be just a dedicated Mod that includes all the Assets, so people can just dump it into the Mods Folder.

**Comment by Roadhog360** [comment] 2023-08-02 20:40
Then if there's a fallback it's not obvious there's something wrong
And I'm not adding 500 checks where new sounds are used to check if the download failed. I don't even know how to check if the download failed anyways.

This is a duplicate of #293 and is possibly fixed in a commit after 2.4.6 anyways

**Closed** 2023-08-02 20:40 UTC
