### ISSUE TITLE
All block textures have an opaque background

### ISSUE THREAD

**Issue by avescarelo** [Roadhog360/Et-Futurum-Requiem#376] opened 2023-10-29 16:48 UTC
Mod version 2.5.1
All textures have an opaque background

![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/236f510d-90af-4072-a6a2-f860e93c9595)
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/bd4a5642-4ffe-4e02-b47c-d94c35b49952)

**Comment by avescarelo** [comment] 2023-10-29 16:51
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/dd7ff7eb-9ab8-4365-8333-2b4331437c2b)

**Comment by Roadhog360** [comment] 2023-10-29 20:06
I have never seen this issue before. Are you possibly using a mod that is wrongfully filling in transparent areas in my textures? Maybe the jar you downloaded is somehow corrupt, what happens if you download the mod again?

**Comment by GregoriusT** [comment] 2023-10-29 20:34
I know this happens when some other Block in that Chunk or anything else rendering in that Chunk, forgets to reset the Alpha handling properly. Now the question is what is the cause? I cant really test because Et Futurums Dev build is currently throwing unrelated Errors at me, because someone assumes 0 and 15 are the bounds by which itemstack metadata goes, even though its 0 to 32767. :P

**Comment by Roadhog360** [comment] 2023-10-29 20:35
Wha? Can you elaborate?

**Comment by Roadhog360** [comment] 2023-10-29 22:47
So yeah, if this happens with no other mods installed, can you please try re-downloading the mod?
Also, it'd help to know the OS you're using, the PNG compression algorithm we use could possibly be a culprit on certain OSs if I were to guess. Send logs, it'll have the OS information I need

**Comment by GregoriusT** [comment] 2023-10-29 23:10
wait wait wait which png compression algo do you use? because i ran into issues with optipng and grayscale textures. Once a png is marked as grayscale, minecraft will NOT be able to render it properly at all (some optipng parameters can easily fix that ofc). Obviously colored Textures wont be hit by that, but if you happen to have a Texture that is 100% grayscale without any color variation, it will happen.

**Comment by Roadhog360** [comment] 2023-10-29 23:21
I use the same compression algorithm that you provided in the `format_all_source_files.sh` that you added. I use that typically before releases to format the code, it seems to also contain some sort of PNG compression in it.

**Comment by GregoriusT** [comment] 2023-10-29 23:32
Yeah that one is fine, it has the right parameters for optipng.

IF you ran optipng at "maximum efficiency" then minecraft wouldn't be able to handle the resulting png files... likely due to the old OpenGL library it uses.

**Comment by Roadhog360** [comment] 2023-10-30 20:56
Any updates on the issue, @avescarelo? Is there a mod conflict, did you try to re-download the jar?

**Comment by avescarelo** [comment] 2023-11-02 18:11
Yes!
I had such a problem with previous versions of the mod, it manifests itself both on Linux and on Windows

**Comment by Roadhog360** [comment] 2023-11-02 20:30
Have you tried removing other mods yet as requested? I'd start with OptiFine

**Comment by avescarelo** [comment] 2023-11-06 12:13
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/53093112-e773-4186-bdf4-163c1ac8b773)

I have no idea why only with this mod i have a crash

Log: [https://gist.github.com/avescarelo/9d399ad0b9db00196611aea859dfe52d](https://gist.github.com/avescarelo/9d399ad0b9db00196611aea859dfe52d)

**Comment by avescarelo** [comment] 2023-11-06 16:25
> Crash logs are kind of useless for class loading errors, a full log (like the one you posted here [#376 (comment)](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/376#issuecomment-1791290105)) would be more helpful.

Yes, here: [https://gist.github.com/avescarelo/5766e2be64b76bda8df2a38f2f66d268](https://gist.github.com/avescarelo/5766e2be64b76bda8df2a38f2f66d268)

**Comment by Roadhog360** [comment] 2023-11-06 18:25
That's weird, I've never seen an error like this without other mods installed o.o

**Comment by GregoriusT** [comment] 2023-11-06 19:47
Is that a Version that has a new Block Renderer in it? Maybe that new Renderer is leaking a GL Setting or so, which one of the Blocks in that particular World happens to use somewhere Underground.

**Comment by makamys** [comment] 2023-11-06 20:07
It looks like some error involving potions happens, but a different error prevents the actual message from getting printed. Now where have I seen this before? Oh yeah: https://github.com/Roadhog360/Et-Futurum-Requiem/issues/258

That issue was caused by potion ID extension mods though. I think the issue this time is improper configuration.

I would suggest creating a fresh instance with a fresh config and testing there for now, since this is unrelated to the texture issue.

I also just pushed an unpushed CoreTweaks branch created to fix this particular logging issue that you can grab [here](https://nightly.link/makamys/CoreTweaks/workflows/gradle/fix-fmllog-crash/Package.zip). Adding it should make it easier to find out why that potion crash happens.

**Comment by Roadhog360** [comment] 2023-11-06 22:28
> Is that a Version that has a new Block Renderer in it? Maybe that new Renderer is leaking a GL Setting or so, which one of the Blocks in that particular World happens to use somewhere Underground.

No otherwise I would have already gotten this texture error. I am also talking about the potion crash anyways

**Comment by Roadhog360** [comment] 2023-11-06 22:29
Yeah maybe somehow it's the potion ID? If levitation's ID is set out of bounds of vanilla (32 or more) it may cause issues.

**Comment by avescarelo** [comment] 2023-11-06 22:40
Yes, sorry for lae answers i removed configs and all is good, now testing add other mods. Only with this mood all is good

**Comment by avescarelo** [comment] 2023-11-06 22:49
[https://disk.yandex.by/d/_yncsdgIvqmqKA](https://disk.yandex.by/d/_yncsdgIvqmqKA)

Also, I saw that someone here wrote about bugs with taumcraft (if I'm not mistaken) and you said that you don't have its source code, maybe it's useful to you, this is the source code of taumcraft to which fixes of various bugs are made

**Comment by avescarelo** [comment] 2023-11-06 23:05
I was found a problem mod, that's because AntiXray mod: [https://rubukkit.org/threads/1-7-2-1-7-10-antixray-reloaded-minecraft-forge.62985/](https://rubukkit.org/threads/1-7-2-1-7-10-antixray-reloaded-minecraft-forge.62985/)

I removed and all is good, this mod remove an opaque of Xray texturepacks

**Comment by GregoriusT** [comment] 2023-11-06 23:45
Which Thaumcraft related Compatibility Issue are you talking about specifically? I do have the thaumcraft source code too, and I know a little bit about how things work in there.

**Comment by avescarelo** [comment] 2023-11-06 23:47
I think it was written about this in one of the reports before, but it doesn't matter, the main thing is that the problem has been solved

**Comment by Roadhog360** [comment] 2023-11-07 01:23
Not sure why antixray was messing up my textures and not the other ones, but glad to see it resolved!

**Closed by Roadhog360** 2023-11-07 01:23 UTC
Labels: Question, Cannot Reproduce

**Comment by Roadhog360** [comment] 2023-11-07 01:27
Side note: For copyright safety I removed the Thaumcraft src here. However I have actually since my last report came across Thaumcraft src and may look at the other issue in the future
