### ISSUE TITLE
shulker_box problem

### ISSUE THREAD

**Issue by zfms4188** [Roadhog360/Et-Futurum-Requiem#147] opened 2022-07-09 00:56 UTC
**Starting Questions**
- [ ] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

_Please specify the actual version... please don't just say "latest", tell me the version number of the mod in-game, or the name the jar had when downloading it._
Version: 2.4
If this is a crash, please upload the report:

**Describe the bug**
_A clear and concise description of what the bug is._
When opening shulker_box, if it is destroyed by others, an extra copy will be dropped

**To Reproduce**
1. Wax a copper block of any kind
2. Using any compatible axe item, right click to scrape it off
3. The game crashes

**Mod Incompatibilities**
_If this was a mod incompatibility, what are the possible suspects? If you're not 100% sure, you can still list your suspected mods here, just tell me if you're not certain they actually cause it._

**Mod List**
_If you have posted a crash report above or this is not a mod incompatibility, you can skip this. If you're filling this out because of a mod incompatibility that isn't a crash, crash reports generate a mods list you can copy. Please use Pastebin if it is large. If you don't have an up-to-date crash report, you can hold F3 + C for 10 seconds while in a world to crash the game, which will give you a crash report._

**Screenshots**

**Additional context**
Any other info I may have missed. If you know the code which causes the error please post a link to it.

**Comment by Roadhog360** [comment] 2022-07-09 00:58
Does not use the template properly, most of the fields remain blank and the example steps to reproduce are not used. Please give me steps to reproduce the issue.

**Comment by zfms4188** [comment] 2022-07-09 01:00
“When opening shulker_box, if it is destroyed by others, an extra copy will be dropped”
Open an shulker_box and then destroy it by someone else, and the thing will drop an empty copy
(Google Translate)

**Comment by Roadhog360** [comment] 2022-07-09 01:05
[simplescreenrecorder-2022-07-08_20.04.30.webm](https://user-images.githubusercontent.com/11903511/178085914-91c8aeba-ea1c-4765-ac2c-f1661ee2f2d5.webm)

I cannot reproduce this, so this is likely a mod conflict. Please actually fill out the template as requested :)

**Comment by zfms4188** [comment] 2022-07-09 01:13
XD
Maybe... It can be destroyed by other means, for example, botania Dig the len
![QQ图片20220709091256](https://user-images.githubusercontent.com/86733104/178086106-63d24f09-8eb8-446b-b829-c109b2610a2a.png)
s

**Comment by zfms4188** [comment] 2022-07-09 01:14
oh,It seems that when the interface is not opened, it will also drop an extra copy

**Comment by GregoriusT** [comment] 2022-07-09 06:42
@Roadhog360 I think your template is a bit difficult to use, you put in way too many "example texts" and that results in people not exactly knowing where to put their real texts. People easily get confused, so it is only natural for this to happen. You cant really enforce something so complicated they dont understand.

**Comment by Roadhog360** [comment] 2022-07-09 12:56
It is not complicated. It asks a question, then elaborates or provides a text. If your report has nothing to do with copper then it is obviously an example.

**Comment by Roadhog360** [comment] 2022-07-09 16:56
This might have been indirectly fixed in a commit. Can you try downloading this zip here and using the jar that does not have "dev" in its name? https://github.com/Roadhog360/Et-Futurum-Requiem/suites/7287056639/artifacts/293714006

> XD Maybe... It can be destroyed by other means, for example, botania Dig the len ![QQ图片20220709091256](https://user-images.githubusercontent.com/86733104/178086106-63d24f09-8eb8-446b-b829-c109b2610a2a.png) s

**Comment by Roadhog360** [comment] 2022-07-11 22:45
As you've reacted with a heart instead of replying, I am going to assume that means the issue is now fixed.

**Closed by Roadhog360** 2022-07-11 22:45 UTC
Labels: Cannot Reproduce
