### ISSUE TITLE
geodes in ocean

### ISSUE THREAD

**Issue by smeegle5000** [Roadhog360/Et-Futurum-Requiem#166] opened 2022-08-11 13:41 UTC
**Starting Questions**
- [no, used solo] This is a mod incompatibility, if I use this in vanilla Forge, with only Et Futurum Requiem installed it works as I'd expect it to.

_Please specify the actual version... please don't just say "latest", tell me the version number of the mod in-game, or the name the jar had when downloading it._
Version: 2.4.0
If this is a crash, please upload the report:

**Describe the bug**
_A clear and concise description of what the bug is._

amethyst geodes generate often freefloating in the ocean

**To Reproduce**
create a world and fly out to sea

**Mod Incompatibilities**
_If this was a mod incompatibility, what are the possible suspects? If you're not 100% sure, you can still list your suspected mods here, just tell me if you're not certain they actually cause it._
none

**Mod List**
_If you have posted a crash report above or this is not a mod incompatibility, you can skip this. If you're filling this out because of a mod incompatibility that isn't a crash, crash reports generate a mods list you can copy. Please use Pastebin if it is large. If you don't have an up-to-date crash report, you can hold F3 + C for 10 seconds while in a world to crash the game, which will give you a crash report._
et futurum
forge

**Screenshots**
![2022-08-11_21 39 38](https://user-images.githubusercontent.com/52786417/184146760-c67e24b5-e2bf-41b4-b595-6705da9dbade.png)

**Additional context**
Any other info I may have missed. If you know the code which causes the error please post a link to it.

expected behaviour is for them to rarely spawn half buried in the ocean

**Comment by makamys** [comment] 2022-08-11 17:07
This is a duplicate of #149, which was fixed in cdedec5.

**Closed** 2022-08-11 18:28 UTC
