### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MesTeiK-git** [Roadhog360/Et-Futurum-Requiem#227] opened 2023-01-22 08:35 UTC
- [x] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.4.2

### Describe the issue (IMPORTANT)
When a player logs on to the server, it crashes both the server and the player himself (the client).
 Server - https://pastebin.com/6yUwwC0c
 Client - https://pastebin.com/Y97tRYnP

### Mod list (OPTIONAL)
> _Crash reports contain the mod list to copy. Please use Pastebin or Gist if it is too large. If you don't have a crash report, open any world and hold F3 + C for 10 seconds to crash the game manually._

### Additional Context (OPTIONAL)
> _Any other info that may have been missed? If you suspect other mods to cause this issue, list them here and tell us why you suspect each of them._

**Comment by Roadhog360** [comment] 2023-01-22 09:30
Duplicate of #216

**Closed** 2023-01-22 09:31 UTC
