### ISSUE TITLE
Ears mod incompatibility

### ISSUE THREAD

**Issue by JeffersonTan** [Roadhog360/Et-Futurum-Requiem#249] opened 2023-02-25 07:27 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.4.3

### Describe the issue (IMPORTANT)
Game crashed on startup

### Mod list (OPTIONAL)
ArchaicFix
Backhand
Campfire Backport
CodeChicken Core
CoreTweaks
D-Mod
Ears
Electrical Age - jrddunbr's build
Et Futurum Requiem
FalsePatternLib
FalseTweaks
Floatingltems
FoamFix
Leaf Culling
Neodymium
NotEnoughltems
Squidless
TcpNoDelayMod-2.0
UniMixins

### Additional Context (OPTIONAL)
I did a bunch of testing myself and it seem like Et-Futurum Requiem has incompatibilities with "ears" mod, I've tried enabling all the mods  I have one-by-one until I've enabled ears and it crashed the game

### Logs
https://paste.ee/p/w9izr

**Comment by GregoriusT** [comment] 2023-02-25 08:20
This is a mixins/asm related thing, so I think that is probably a job for makamys ;)

**Comment by Roadhog360** [comment] 2023-02-25 18:30
embeddedt created the Elytra code. Although I'll have to double-check if I can reproduce this later.

**Comment by makamys** [comment] 2023-02-25 20:40
This happens because FoamFix [loads Ears classes during coremod initialization](https://github.com/asiekierka/FoamFix17/blob/ef09c29084bbe403d8c6d6b8079ebf70dc378fc5/src/main/java/pl/asie/foamfix/bugfixmod/coremod/BugfixModClassTransformer.java#L186), and said classes reference ModelBiped. Turn off `mc18SkinSupport` in FoamFix to fix the issue (it's supposed to get auto-disabled when Ears is present anyway).

**Comment by makamys** [comment] 2023-02-26 13:51
Fixed in https://github.com/asiekierka/FoamFix17/commit/41700ec1965487791fb7327307572caf37041fdb

**Closed by makamys** 2023-02-26 13:51 UTC
