### ISSUE TITLE
ExtraUtilities's DivisionSigil Activation Abnormality

### ISSUE THREAD

**Issue by Ventivu** [Roadhog360/Et-Futurum-Requiem#347] opened 2023-09-30 09:09 UTC
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.5.0

### Describe the issue (IMPORTANT)

Tweaked Enchanting Table Tile cause "ExtraUtilities:divisionSigil" cannot be activated normally

**Comment by Roadhog360** [comment] 2023-09-30 10:38
You already reported this.
Duplicate of #311

**Closed by Roadhog360** 2023-09-30 10:38 UTC
