### ISSUE TITLE
Rabbits spawn in the worlds of DivineRPG and in the Twilight Forest

### ISSUE THREAD

**Issue by VadimFlex** [Roadhog360/Et-Futurum-Requiem#417] opened 2024-01-28 14:19 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.5.1

### Describe the Issue

In DivineRPG rabbits spawn in Edem and Wildwood. As for the rest of the worlds, I can't say for sure. Rabbit spawn also occurs in the Twilight Forest.
![2024-01-21_17 38 48](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/768c2c0a-66b8-4b0a-9932-1212be066114)
![2024-01-21_19 12 11](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/92884289-e753-476d-8d52-791c909ad7cf)

### Conflicting Mods

DivineRPG, Twilight Forest

**Comment by Roadhog360** [comment] 2024-01-28 16:03
Mods use biome tags. Worldgens and spawns arenot limited to overworld

**Comment by VadimFlex** [comment] 2024-01-28 16:38
> Mods use biome tags. Worldgens and spawns arenot limited to overworld

Then why don't vanilla mobs, which absolutely also have biome tags, spawn in the worlds of these mods?

**Comment by Roadhog360** [comment] 2024-01-28 16:41
> > Mods use biome tags. Worldgens and spawns arenot limited to overworld
> 
> Then why don't vanilla mobs, which absolutely also have biome tags, spawn in the worlds of these mods?

Idk probably lazy vanilla mob only removal or removal initializes too early to detect modded mobs. In that case it's not my bug.

Just Another Spawner can probably manage this

**Comment by VadimFlex** [comment] 2024-01-28 16:52
> removal initializes too early to detect modded mobs

This situation only happens with the EFR rabbit. Mobs from other mods  do not spawn.

> Just Another Spawner can probably manage this

As far as I remember, this mod breaks spawn in some mods. And Divine rpg is on this list.

**Comment by Roadhog360** [comment] 2024-01-28 16:54
> As far as I remember, this mod breaks spawn in some mods. And Divine rpg is on this list.

And this mysterious new bug hasn't been reported because…?

**Comment by VadimFlex** [comment] 2024-01-28 17:21
> And this mysterious new bug hasn't been reported because…?
Because the latest version of JAS was released in 2017, and the first version of DivineRPG 1.7.10 in 2020. Which already significantly reduces the number of requests on this topic. I know for sure that DivineRPG did not work with several mods for changing spawn mobs that I tested. It works, but incorrectly. But in any case, it requires additional testing on my part to tell for sure whether JAS was among them or not. But based on the github of this mod, I know that it has problems with spawning vanilla squid.

**Comment by Roadhog360** [comment] 2024-01-28 17:22
I thought "this mod" referred to this mod... EFR, mb

**Comment by VadimFlex** [comment] 2024-01-28 17:28
> I thought "this mod" referred to this mod... EFR, mb

This is probably the result of my poor knowledge of English. And google translate)

**Comment by VadimFlex** [comment] 2024-01-28 17:55
> I thought "this mod" referred to this mod... EFR, mb

So my message about the mod that breaks spawn mobs was about JAS, which you suggested to solve the problem.

**Comment by Roadhog360** [comment] 2024-01-28 17:56
That's news to me, I've heard people talking about it all the time to modify mob spawns

**Comment by VadimFlex** [comment] 2024-01-28 18:38
Sorry to ask here, I just don't know where it can be done. Where can I download the alpha version of EFR 2.6.0?

**Comment by GregoriusT** [comment] 2024-01-30 00:29
Uh I have never seen Et Futurum Requiems Rabbits in Twilight Forest, are you sure that you dont confuse them with Twilight Bunnies? (GT6 even makes it so that those Bunnies drop the same stuff EFRs Rabbits drop)

**Comment by VadimFlex** [comment] 2024-01-30 01:55
> Э-э, я никогда не видел кроликов Et Futurum Requiems в Сумеречном лесу, ты уверен, что не путаешь их с Сумеречными кроликами? (GT6 даже делает так, что из этих кроликов выпадает то же самое, что и из кроликов EFR)

![2024-01-30_04 03 33](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/3faedf7f-f2a9-4196-bb50-8c3bdb7433bc)
![2024-01-30_03 48 42](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/132595752/892d0875-684e-416a-8372-3af9d450528a)

**Comment by VadimFlex** [comment] 2024-01-30 02:03
> You can either click the green checkmark next to any commit message or go to the actions tab and click on the latest commit. Under the `summary` tab is a package you can download. Do not use the `dev` builds unless you are in an IDE

Thanks for the information)

I also noticed that in the Iceika world, skeletons from DivineRPG are being redefined to skeletons from EFR (not all, but most of them). Also, with EFR installed, fewer DivineRPG mobs will spawn in this world for some reason.

**Comment by Roadhog360** [comment] 2024-01-31 05:45
> > You can either click the green checkmark next to any commit message or go to the actions tab and click on the latest commit. Under the `summary` tab is a package you can download. Do not use the `dev` builds unless you are in an IDE
> 
> Thanks for the information)
> 
> I also noticed that in the Iceika world, skeletons from DivineRPG are being redefined to skeletons from EFR (not all, but most of them). Also, with EFR installed, fewer DivineRPG mobs will spawn in this world for some reason.

EFR skeletons? You mean strays? EFR only replaces vanilla skeletons though

**Comment by VadimFlex** [comment] 2024-01-31 21:59
> You mean strays?

Yes, that's what I mean.

> (Is **Ice**ika a cold world with cold biomes?)

Yes, it's a cold world

> unless DivineRPG overwrites the vanilla skeleton in the mob registry.

I think DivineRPG is overwriting vanilla skeletons. The same thing EFR does and it creates a problem

**Comment by Roadhog360** [comment] 2024-01-31 22:01
Strays are designed to replace vanilla skeletons, or whatever overwrites them. If any mod replaced vanilla skeletons then my replacement wouldn't work if it only worked on vanilla skeletons. This is the feature, working as intended.

**Comment by VadimFlex** [comment] 2024-01-31 22:10
> This is the feature, working as intended.

Why are skeletons being overwritten in the worlds of other mods? I think this is appropriate only in overworld

**Comment by Roadhog360** [comment] 2024-01-31 22:12
It's biome-dependent, and it's not world-dependent for the same reason why other overworld features are not locked to the overworld.

I think this is getting off-topic, for more general unrelated discussion you can use the CurseForge comments or join the Discord server

**Comment by VadimFlex** [comment] 2024-01-31 22:22
> It's biome-dependent, and it's not world-dependent for the same reason why other overworld features are not locked to the overworld.

As I understand it, you have the same opinion about spawning rabbits from your mod. Which is strange, because many mods for mobs with different worlds spawn these mobs exclusively in the worlds for which they are intended. But this is an absolutely unimportant thing, unlike the fact that your mod breaks the spawn of mobs from other mods

**Comment by Roadhog360** [comment] 2024-01-31 22:25
Do you have a source on the claim that supposedly breaks other mod spawns? Just because it only happens when EFR is in your set up does not mean it is caused by it; multi mod conflicts exist.

**Comment by Roadhog360** [comment] 2024-01-31 22:28
If stays and husks are not working correctly in your setup then you can enable "old" behavior (which spawns them as normal mobs instead of replacements) or turn them off entirely...

**Comment by GregoriusT** [comment] 2024-02-01 02:08
The Event you use to replace Skeletons, would it make sense to have "latest" as priority for it, so that other mods can replace the skeletons first?

**Comment by Roadhog360** [comment] 2024-02-01 04:27
Sure, but that wouldn't fix this particular issue since DivineRPG skeletons seem to be registry replacements as far as I can tell. I might blacklist specifically DivingRPG's dimension from my logic... but I want to find out *why* specifically rabbits seem to make it through when other modded animals don't.

I have a sneaking suspicion that the mods in question add stuff by biomes themselves, whilst I add mobs to biomes via their BiomeDictionary tags. I'm gonna do a code analysis on DivingRPG to get to the bottom of this.

**Comment by GregoriusT** [comment] 2024-02-01 06:24
By the way, making Twilight Forests small Bunnies drop the same Stuff Rabbits do might be an Idea, though its not strictly necessary. (they drop absolutely nothing right now, except when gt6 adds the efr items as drops)

**Comment by Roadhog360** [comment] 2024-02-01 06:37
If you hand off your code to do that to me, I can add it

**Comment by VadimFlex** [comment] 2024-02-02 22:51
> Do you have a source on the claim that supposedly breaks other mod spawns?

I have checked all the issues I wrote about here and got the following conclusions:

1)Rabbits will spawn in twilight forest (even if only **Twilight forest** is installed)

2)Rabbits spawn in some DivineRPG worlds (even if only **DivineRPG** is installed)

3) Strays will not spawn in the DivineRPG world and overworld ( if only DivineRPG and EFR are installed)

The third problem is the most interesting. If only EFR is installed, then stray will not spawn either. Which surprised me a lot, because you don't recommend Optifine. And if you install more Optifine, then they begin to appear. Well, accordingly, if you install DivineRPG, then EFR overwrites skeletons from DivineRPG

**Comment by VadimFlex** [comment] 2024-02-02 22:52
> > Есть ли у вас источник утверждения, которое якобы нарушает создание других модов?
> 
> Я проверил все проблемы, о которых писал здесь, и пришел к следующим выводам:
> 
> 1)Кролики будут спавниться в сумеречном лесу (даже если ** только Сумеречный лес ) ** установлен
> 
> 2)В некоторых мирах DivineRPG спавнятся кролики (даже если ** ​​только DivineRPG ) ** установлена
> 
>     3. Бродяги не будут появляться в мире DivineRPG и в остальном мире (если установлены только **DivineRPG** и **EFR**)
> 
> 
> Третья проблема – самая интересная. Если установлен только EFR, то и бродяги не спавнятся. Что меня очень удивило, ведь вы не рекомендуете Optifine. А если установить еще Optifine, то они начинают появляться. Ну и соответственно если установить DivineRPG, то EFR перезаписывает скелеты из DivineRPG

**Comment by GregoriusT** [comment] 2024-02-02 23:38
Excuse me, did you just say Optifine changes more about Mob Spawns, than just screwing up Blocks that prevent Mob Spawning?! What the hell is that Mod doing, this is way out of scope for an optimization Mod...

**Comment by Roadhog360** [comment] 2024-02-03 01:00
> Excuse me, did you just say Optifine changes more about Mob Spawns, than just screwing up Blocks that prevent Mob Spawning?! What the hell is that Mod doing, this is way out of scope for an optimization Mod...

Yes, it breaks the mob spawn event so I have to enable the old behavior which is just simply adding husks and strays to the mob spawn list, because the code that replaces them is broken by OptiFine.

**Comment by VadimFlex** [comment] 2024-02-05 01:49
> Excuse me, did you just say Optifine changes more about Mob Spawns, than just screwing up Blocks that prevent Mob Spawning?!

As I understand it, this is exactly the case. But Optifine no longer surprises me with this. It surprises me that EFR cannot spawn strays without Optifine.

**Comment by Roadhog360** [comment] 2024-02-05 01:51
> > Excuse me, did you just say Optifine changes more about Mob Spawns, than just screwing up Blocks that prevent Mob Spawning?!
> 
> As I understand it, this is exactly the case. But Optifine no longer surprises me with this. It surprises me that EFR cannot spawn strays without Optifine.

As I have already explained, EFR uses different spawning logic for husks and strays when OptiFine is installed.

**Comment by VadimFlex** [comment] 2024-02-05 01:55
> As I have already explained, EFR uses different spawning logic for husks and strays when OptiFine is installed.

Hmm, what is the other logic? I couldn't find strays without Optifine

**Comment by Roadhog360** [comment] 2024-02-12 06:42
Another mod might be interfering with the event then. If another mod is replacing skeletons with a different mob that would prevent Et Futurum from doing its stray replacement. Unfortunately I cannot do anything about that.
If you find strays in DivingRPG's ice world with only OptiFine that means that a mod is replacing skeletons (and might be replacing zombies too) with a non-vanilla version. The reason why it works with OptiFine, is because OptiFine breaks the event I utilize to replace skeletons, so I just add them to the spawn list instead of replacing.

> If strays and husks are not working correctly in your setup then you can enable "old" behavior (which spawns them as normal mobs instead of replacements) or turn them off entirely...

May I reference you to this reply, and I'll amend it. This functionality can be found in `world.cfg` under `oldHuskSpawning` and `oldStraySpawning`, which enables the different logic without OptiFine. Since OptiFine breaks the "new" behavior, I force these options to be used when it is present.

**Comment by Roadhog360** [comment] 2024-02-12 06:45
I've decided to just make rabbits ignore divinerpg worlds. I don't really know why they are there in the first place or why other mobs don't spawn there, or exactly what is breaking my spawn behavior, but I hope this fix works. I will text it when I have time.

**Closed** 2024-02-12 06:44 UTC
