### ISSUE TITLE
Crash when looking up recipes that involve Shulker Box upgrades

### ISSUE THREAD

**Issue by krallendertoten** [Roadhog360/Et-Futurum-Requiem#230] opened 2023-02-06 21:31 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [x ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

-- Head --
Stacktrace:
	at ganymedes01.etfuturum.items.ItemGeneric.func_77617_a(ItemGeneric.java:39)
	at net.minecraft.item.Item.func_77650_f(Item.java:440)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)

-- Item being rendered --
Details:
	Item Type: ganymedes01.etfuturum.items.ItemShulkerBoxUpgrade@485080d2
	Item Aux: 4
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:503)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)

- [ x] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.4.2

### Describe the issue (IMPORTANT)

Looking up the uses for any item that would be used to upgrade a shulker box (iron, obsidian, gold, etc.), or the shulker box itself in NEI causes the game to crash with the above error. It seems to be an issue with the way the Iron Chests integration is happening. I can't reproduce this in instances with or without Iron Chests in it; only when adding Et Futurum Requiem to Blightfall 3.0.1-CE does this happen, which does not have Iron Chests in its mod list

Modlist:

 00gasstation-mc1.7.10-0.5.1.jar
 1.7.10
 AppleCore-mc1.7.10-3.1.1.jar
 ArchimedesShips-1.7.1.jar
 ArmorStatusHUD-client-1.28.jar
 Aroma1997Core-1.7.10-1.0.2.16.jar
 AromaBackup-1.7.10-0.1.0.0.jar
 Automagy-1.7.10-0.28.2.jar
 BetterFps-1.0.1.jar
 BetterStorage-1.7.10-0.13.1.126-nosplode.jar
'BiblioCraft[v1.11.7][MC1.7.10].jar'
'BiblioWoods[Natura][v1.4].jar'
 BigReactors-0.4.3A.jar
 BloodMagic-1.7.10-1.3.4-blight.jar
 Botania+r1.7-208.jar
 ChickenChunks-1.7.10-1.3.4.19-universal.jar
 Chisel-1.7.10-1.5.7.jar
'CoFHCore-[1.7.10]3.1.4-329.jar'
 CodeChickenCore-1.7.10-1.0.7.48-universal.jar
 Controlling-1.7.10-1.0.0.jar
 CoreTweaks-1.7.10-0.3.0.1.jar
 CosmeticArmorReworked-1.7.10-v7.jar
 CustomNPCs-1.7.10c-herohack3.jar
 EnderStorage-1.7.10-1.4.7.37-universal.jar
 Et_Futurum_Requiem-2.4.2.jar
 ExtraCells-1.7.10-2.3.14b200.jar
 ExtraTiC-1.7.10-1.4.6.jar
 ExtraUtilitiesTweaks-1.0.0.jar
 FoamFix-1.7.10-universal-1.0.2.jar
'Forbidden Magic-1.7.10-0.575.jar'
 ForgeMultipart-1.7.10-1.2.0.345-universal.jar
'HQM-The Journey (4.2.3).jar'
 HelpFixer-1.0.7.jar
 HungerOverhaul-1.7.10-1.0.0-ConfigHack-2.jar
'INpureCore-[1.7.10]1.0.0B9-62.jar'
 IguanaTinkerTweaks-1.7.10-2.1.6.jar
 ImLookingAtBlood-1.7.2-1.1a.jar
 Jabba-1.2.2_1.7.10.jar
 Lockdown-2.0.0.0.jar
 LumySkinPatch-1.0.10.jar
 LunatriusCore-1.7.10-1.1.2.21-universal.jar
 Mantle-1.7.10-0.3.2b.jar
 Metallurgy-1.7.10-4.0.9.148.jar
 MetallurgyCore-1.7.10-4.0.5.30.jar
'MineFactoryReloaded-[1.7.10]2.8.1-174.jar'
 MineTweaker3-1.7.10-3.0.10B.jar
 MobiusCore-1.2.5_1.7.10.jar
 ModTweaker2-0.9.6.jar
 ModelCitizens-mc1.7.10-1.0.1.jar
 MouseTweaks-2.4.4-mc1.7.10.jar
 NEIPlugins-MC1.7.10-1.1.0.10-unofficial.jar
'NetherOres-[1.7.10]2.3.1-22.jar'
 NotEnoughItems-1.7.10-2.1.5-GTNH-universal.jar
 OptiFine_1.7.10_HD_U_D6.jar
"Pam's HarvestCraft 1.7.10Lb.jar"
 PerfectSpawn-1.1.jar
 PlayerAPI-1.7.10-1.4.jar
 RPGAdvMod-1.0.0_1.7.10.jar
'RedstoneArsenal-[1.7.10]1.1.2-92.jar'
 Satchels-1.7.10-1.0.7.jar
 Schematica-1.7.10-1.7.5-GenHack3.jar
 SleepingBag-1.7.10-0.1.1.jar
 SpiceOfLife-mc1.7.10-1.3.11.jar
 StorageDrawers-1.7.10-1.10.9.jar
 TConstruct-1.7.10-1.8.8.jar
 TMechworks-1.7.10-0.2.15.106.jar
'TabulaRasa-[1.7.10]1.0.1-3-Blight4.jar'
 TaintedPlayers-v1.1-1.7.10.jar
 TerrainControl
 Thaumcraft-1.7.10-4.2.3.5.jar
 ThaumicTinkerer-2.5-1.7.10-blight.jar
'ThermalDynamics-[1.7.10]1.2.1-172.jar'
'ThermalExpansion-[1.7.10]4.1.5-248.jar'
'ThermalFoundation-[1.7.10]1.2.6-118.jar'
 TiCTooltips-mc1.7.10-1.2.4.jar
 TooMuchLoot-1.7.10-4.0.1.B0.jar
 Translocator-1.7.10-1.1.2.16-universal.jar
 UBCOres-1.7.10-0.2.9.4.jar
 UndergroundBiomesConstructs-1.7.10-0.8-beta49.jar
 VoxelMods
 Waila-1.5.10_1.7.10.jar
 WailaHarvestability-mc1.7.10-1.1.6.jar
'[1.7.10]StatusEffectHUD-client-1.27.jar'
 appliedenergistics2-rv3-beta-6.jar
 betterrain-1.7.2-1.7.10_0.15-core.jar
 betterrain-1.7.2-1.7.10_0.15.jar
 blightbuster-2.0.5.jar
 blightcore-1.3.0.jar
 blightfall-filefix-v1.0.0.jar
 cookingbook-mc1.7.10-1.0.140.jar
 extrautilities-1.2.12.jar
 falsepatternlib-mc1.7.10-0.10.14.jar
 falsetweaks-mc1.7.10-2.2.1.jar
 fastcraft-1.23.jar
 inventorytweaks-1.58-147.jar
 leafculling-mc1.7.10-1.0.9.jar
 liteloader-1.7.10.jar
 mixingasm-1.7.10-0.2.2.jar.disabled
 mod_voxelMap_1.7.0b_for_1.7.10.litemod
 natura-1.7.10-2.2.0.1.jar
 neiaddons-1.12.14.40-mc1.7.10.jar
 neodymium-1.7.10-0.1.6.jar
 netherless-1.0.jar
 newradicalbotany-1.1.2.jar
 notimefix-2.1.0.jar
 purplepanic-1.0.6.jar
 ssmlegacy-mc1.7.10-1.2.0.jar
 tcinventoryscan-mc1.7.10-1.0.11.jar
 tcnodetracker-1.7.10-1.1.2.jar
 terraincontrol-forge-2.7.0-colored-lockhack-spawnfix.jar
 thaumcraftneiplugin-1.7.10-1.7a.jar
 thaumicenergistics-1.1.3.0.jar
 thaumichorizons-1.7.10-1.1.9.jar

**Comment by Roadhog360** [comment] 2023-02-06 21:32
Please use Pastebin or another text website and include the full report.

**Comment by krallendertoten** [comment] 2023-02-06 21:42
https://pastebin.com/UvLvkjJf

**Comment by Roadhog360** [comment] 2023-02-18 21:57
I can't reproduce this so this is a mod conflict. I fixed some different issues regarding them, so try the latest CI and if that fixes it I can close this.

**Comment by GregoriusT** [comment] 2023-02-18 22:36
I can tell you right away this is NOT a mod conflict. What is likely happening is that something returns an illegal value somewhere within EFR Code. In this case it is a very clear cut Issue, see:

https://github.com/Roadhog360/Et-Futurum-Requiem/blob/master/src/main/java/ganymedes01/etfuturum/items/ItemGeneric.java#L39

"icons" is clearly null because it did not get assigned for one of the things you recently added.

**Comment by Roadhog360** [comment] 2023-02-19 08:37
It has to be a mod conflict because NEI nor creative causes it = mod causes it

**Comment by GregoriusT** [comment] 2023-02-19 13:08
Uhm i dont know if you noticed, but the crash happens while the Item is rendered, which means the Game has to have already put all the "icon" Arrays into place at this point.

Also it is the "diamond_obsidian_upgrade" that specifically is crashing according to the Logs. Weirdly enough when I look into that Class it does not have anything suspicious in it, it SHOULD assign the icon Array, but for some reason it does not, which leads me to believe that you are adding an Item to a Creative Tab that is NOT in the ItemRegistry, and therefore WONT have registerIcons called ever, and therefore will crash the instant you try to render it.

Remembering IronChests is NOT installed, yet the Upgrade Item exists at all, means something is broken with your way to detect IronChests, and look at that I think I found it!

https://github.com/Roadhog360/Et-Futurum-Requiem/blob/master/src/main/java/ganymedes01/etfuturum/recipes/ModRecipes.java#L862

This Line is the Issue! Literally everywhere else you check `EtFuturum.hasIronChest && ConfigBlocksItems.enableShulkerBoxesIronChest` but HERE you do not! Resulting in a Crafting Recipe for an unavailable Item being registered, which results in this Error!

**Comment by Roadhog360** [comment] 2023-02-19 20:21
I don't see how recipes would cause this crash but ok

**Closed** 2023-02-19 20:24 UTC
