### ISSUE TITLE
Tinker construct raw or outputs wrong molten liquid

### ISSUE THREAD

**Issue by ShadowsFang** [Roadhog360/Et-Futurum-Requiem#465] opened 2024-05-18 21:50 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et Futurum Requiem 2.6.0 Beta 2 and all versions post 2.5.1

### Describe the Issue

I'm sorry for bringing this to your attention despite the fact that it may not be a problem with your mod specifically, but nobody in the ftb discord or subreddit has responded so I was hoping for help troubleshooting an issue that is affecting your mod within my modpack's ecosystem.

The following was copy-pasted from my Discord message, and I'm too lazy to edit:
Ok, so I'm having a mod compatibility issue that I don't know the source of with Et Futurum Requiem (1.7.10) where the raw gold and raw iron don't smelt in the TConstruct smeltery and none of the raw ores work with Mekanism ore refining. It wasn't a problem until I updated Et Futurum but it still doesn't happen when I remove all other mods except those 3 and their dependencies so I'm not even sure if I should bring it to the mod author's attention.
Again, sorry for bringing it to you.

### Other Details

[mods.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/15366927/mods.txt)
[latest.log](https://github.com/Roadhog360/Et-Futurum-Requiem/files/15366928/latest.log)

**Comment by Roadhog360** [comment] 2024-05-18 23:09
Probably Mekanism's fault since I use OreDict tags properly so it'd be on them to use them.

You are not on the latest EFR beta and you need to update

**Comment by ShadowsFang** [comment] 2024-05-19 02:17
https://drive.google.com/drive/folders/1g4tVNZdfTVcYR8XT_AbznLlVbAnM8AaQ?usp=drive_link
Here's the log/mod list
Like I said, they both work fine outside of the pack.
And I first noticed it on the latest version

**Comment by Roadhog360** [comment] 2024-05-19 15:05
You still haven't tried updating to the latest beta (which is release candidate 1)

**Comment by ShadowsFang** [comment] 2024-05-20 00:35
Ok, updated and replaced the log and mod list files at the same link

**Comment by Roadhog360** [comment] 2024-05-20 00:46
Gotcha

**Comment by ShadowsFang** [comment] 2024-05-25 07:38
Ok, after extensive testing (it's been hours and I haven't fully finished) I've learned that it's at least 2 different mods causing this. I don't know what's causing the Mekanism problem (yet) but I have determined the the root of the TCon problem. 
It's the Ars Magica 2 addon AM2 Playground, specifically: 
AM2PlayGround-Beta-0.11.2
I will resume my search for the source of the Mek problem tomorrow

**Comment by Roadhog360** [comment] 2024-05-25 14:32
Ah, thanks. If you give me the mods and configs for your setup I can try to help now that I have a chance. I noticed that AM2 playground has Tinker's integration, I'm betting something in there probably is broken.

**Comment by Roadhog360** [comment] 2024-05-25 14:36
Suppose I should tag @AirBurn0 in the meantime?

**Comment by AirBurn0** [comment] 2024-05-25 20:47
> Suppose I should tag @AirBurn0 in the meantime?

Indeed!

> Ok, after extensive testing (it's been hours and I haven't fully finished) I've learned that it's at least 2 different mods causing this. I don't know what's causing the Mekanism problem (yet) but I have determined the the root of the TCon problem. It's the Ars Magica 2 addon AM2 Playground, specifically: AM2PlayGround-Beta-0.11.2 I will resume my search for the source of the Mek problem tomorrow

Please consider providing more info, cuz I don't understand at all what's going on.
Test it with minimum mods needed to reproduce the bug, give some logs on this specific error, or maybe some screenshots/video? Put it in new [issue](https://github.com/AirBurn0/am2playground/issues) in mod's repo. I'll seek for solu asap.

**Comment by Roadhog360** [comment] 2024-05-25 20:50
Basically my "raw ore" chunks aren't usable in the smeltery when your AM2 playground mod is installed. I would be testing right now but my internet picked a really shitty time to go down. Thanks Spectrum

**Comment by AirBurn0** [comment] 2024-05-25 21:14
> Basically my "raw ore" chunks aren't usable in the smeltery when your AM2 playground mod is installed. I would be testing right now but my internet picked a really shitty time to go down. Thanks Spectrum

![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/69804577/a7463d02-b961-41ba-9823-175fb186f215)

Got no AM2PG on, and only "Raw Copper" and "Raw Aluminium" is smeltable for me
Also got "Molten Gold" after smelting "Raw Copper" and "Molten Tin" after smelting "Raw Aluminium"

![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/69804577/c3db4fdc-bc6b-4ecc-876e-b1b029a89d33)

Are you sure that it's AM2PG error?

**Comment by Roadhog360** [comment] 2024-05-25 21:15
Wtf

**Comment by AirBurn0** [comment] 2024-05-25 21:16
> Wtf

idk, used [this(https://github.com/Roadhog360/Et-Futurum-Requiem/releases/tag/2.6.0) ver

**Comment by Roadhog360** [comment] 2024-05-25 21:29
I just checked on my end and the raw ores melt down to the correct material, so *some* mod is messing it up, may not be yours after all. The apparent issue as far as I understood though is that the raw ores were not meltable at all, this seems different.

**Comment by Roadhog360** [comment] 2024-05-25 21:35
> ![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/69804577/6f1941ca-73f2-4c38-b66e-d0d62777d20d)

Lmao

**Comment by AirBurn0** [comment] 2024-05-25 21:45
> I just checked on my end and the raw ores melt down to the correct material, so _some_ mod is messing it up, may not be yours after all. The apparent issue as far as I understood though is that the raw ores were not meltable at all, this seems different.

Blood Arsenal and AM2PG can cause that. It working correctly without that mods.
Blood Arsenal has TiC integration also.

**Comment by Roadhog360** [comment] 2024-05-25 21:57
The thing is my code only adds the correct recipes, as it registers it using the material directly related to the raw ore, so I don't know what in my mod there is to fix, which is why I think something else is messing it up and shifting things around,

**Comment by AirBurn0** [comment] 2024-05-25 22:16
> The thing is my code only adds the correct recipes, as it registers it using the material directly related to the raw ore, so I don't know what in my mod there is to fix, which is why I think something else is messing it up and shifting things around,

With Alfheim recipes seems to work correctly, even though there is TIC integration.
Needs more testing with [some of those mods](https://legacy.curseforge.com/minecraft/mc-mods/tinkers-construct/relations/dependents?filter-related-dependents=2), but already seems like AM2PG error for me, so I'll look for it. And probably I have some bad news for Arcaratus...

**Comment by Roadhog360** [comment] 2024-05-25 22:28
I tried Blood Arsenal but my recipes also showed up correctly with it.

**Comment by Roadhog360** [comment] 2024-05-25 23:06
I tried it with AM2 playground as well as Blood Arsenal and my raw ore recipes are still correct

**Comment by ShadowsFang** [comment] 2024-05-25 23:19
After further testing, the mods:
Applied Integrations
and
CC Transport (which I can not find the mod page for anymore)
both interfere with both Mek and TiC recipes for raw ores

**Comment by Roadhog360** [comment] 2024-05-25 23:40
Can you please give me your mods/configs folder containing the minimal mods needed to reproduce the issue?

**Comment by ShadowsFang** [comment] 2024-05-26 06:40
Sure, give me a while though. I have other stuff to do

**Comment by OvermindDL1** [comment] 2024-06-11 03:14
> Can you please give me your mods/configs folder containing the minimal mods needed to reproduce the issue?

Yeah I'm curious about this as well...

**Comment by Roadhog360** [comment] 2024-06-18 18:57
> Sure, give me a while though. I have other stuff to do

Still busy? Just a reminder @ShadowsFang

**Comment by Roadhog360** [comment] 2024-07-01 05:59
Is this still reproducible?

**Comment by Roadhog360** [comment] 2024-07-07 22:12
Closing due to months of information requested not being given and unable to reproduce. If you can still reproduce this, you can leave a comment here for me to reopen and I'll do it

**Closed by Roadhog360** 2024-07-07 22:12 UTC
