### ISSUE TITLE
Thaumcraft native clusters don't drop with raw ores enabled

### ISSUE THREAD

**Issue by DomobotX** [Roadhog360/Et-Futurum-Requiem#100] opened 2022-01-06 06:58 UTC
Version: 2.3.1
When mining vanilla iron and gold (and EFR copper) with TC's Pickaxe of the Core and raw ores enabled, native clusters don't drop, although the little ding indicating so happens. I totally understand if it can't be fixed from this end, or even if it's just not worth it when Fortune III makes the clusters pretty pointless...

**Comment by Roadhog360** [comment] 2022-01-17 22:56
Hm? What happened?

**Comment by DomobotX** [comment] 2022-01-18 18:44
Thought it was a silly thing to ask about.

**Comment by Roadhog360** [comment] 2022-01-23 05:20
If it's an issue caused by this mod it's not a very silly issue. Can you please elaborate?

**Comment by DomobotX** [comment] 2022-01-29 17:51
Well alright.

There's not much to elaborate on, Thaumcraft's Pickaxe of the Core normally has a chance of causing iron, gold, and (if added by a mod, copper) ore blocks to drop a 'native cluster' that smelts for 2 ingots. Fortune increases this chance of happening, I believe. With raw ores enabled, this doesn't happen. If I had to guess TC is watching for the ore block to replace specifically.
I was just thinking it was a little silly to ask about since, again, any FIII pickaxe outdoes the PotC now. If anything could be done about it, it'd be neat if the chance for clusters could run on each individual raw ore chunk, though maybe at a reduced rate than what the PotC usually produces.

**Comment by embeddedt** [comment] 2022-06-24 00:55
The fix here should theoretically be as simple as adding this function to `CompatTC` and calling it where `fixAspects` is called:

```java
        /**
	 * Make raw ores drop native clusters. Copper is handled by Thaumcraft through the ore dictionary.
	 */
	public static void fixPickaxeOfCore() {
		/* iron */
		Utils.addSpecialMiningResult(new ItemStack(ModItems.raw_ore, 1, 1), new ItemStack(ConfigItems.itemNugget, 1, 16), 1.0F);
		/* gold */
		Utils.addSpecialMiningResult(new ItemStack(ModItems.raw_ore, 1, 2), new ItemStack(ConfigItems.itemNugget, 1, 31), 0.9F);
	}
```

Unfortunately, this seems to only work on regular ore blocks for some reason, and not deepslate ore blocks. It doesn't make sense because they both drop the same item. :confused:

**Comment by Roadhog360** [comment] 2022-06-24 02:57
Is it related to how deepslate ores are added to registries during onLoadCompleteEvent?

**Comment by Roadhog360** [comment] 2022-07-17 14:43
Honestly forgot about this. Will investigate.

**Comment by Roadhog360** [comment] 2022-07-17 16:49
[simplescreenrecorder-2022-07-17_11.48.07.webm](https://user-images.githubusercontent.com/11903511/179416115-c7cd7cb8-0455-4b56-bc7b-fed33cecd450.webm)
@DomobotX I cannot reproduce this, even with raw ore enabled it still drops just fine.

**Comment by Roadhog360** [comment] 2022-07-17 17:15
I can also confirm deepslate ores don't actually work despite being registered as an ore.

While I'm here, maybe the clusters don't drop if you don't have raw ores registered as an ore. Do you have the option to register the raw ore item as an ore?

**Comment by GregoriusT** [comment] 2022-07-17 21:58
from "thaumcraft.common.lib.utils.Utils"
```
   public static void addSpecialMiningResult(ItemStack in, ItemStack out, float chance) {
      specialMiningResult.put(Arrays.asList(new Object[]{in.getItem(), Integer.valueOf(in.getItemDamage())}), out);
      specialMiningChance.put(Arrays.asList(new Object[]{in.getItem(), Integer.valueOf(in.getItemDamage())}), Float.valueOf(chance));
   }

   public static ItemStack findSpecialMiningResult(ItemStack is, float chance, Random rand) {
      ItemStack dropped = is.copy();
      float r = rand.nextFloat();
      List ik = Arrays.asList(new Object[]{is.getItem(), Integer.valueOf(is.getItemDamage())});
      if(specialMiningResult.containsKey(ik) && r <= chance * ((Float)specialMiningChance.get(ik)).floatValue()) {
         dropped = ((ItemStack)specialMiningResult.get(ik)).copy();
         dropped.stackSize *= is.stackSize;
      }

      return dropped;
   }
```
I think you can add your Raw Copper ore item to this registry.

**Comment by DarianLStephens** [comment] 2022-07-17 22:42
> Also yes, Azanor loves using THREE spaces instead of Tabs...
Maybe that was just the program they used? It might still be tabs, just converted to spaces?

**Comment by Roadhog360** [comment] 2022-07-21 01:14
> from "thaumcraft.common.lib.utils.Utils"
> 
> ```
>    public static void addSpecialMiningResult(ItemStack in, ItemStack out, float chance) {
>       specialMiningResult.put(Arrays.asList(new Object[]{in.getItem(), Integer.valueOf(in.getItemDamage())}), out);
>       specialMiningChance.put(Arrays.asList(new Object[]{in.getItem(), Integer.valueOf(in.getItemDamage())}), Float.valueOf(chance));
>    }
> 
>    public static ItemStack findSpecialMiningResult(ItemStack is, float chance, Random rand) {
>       ItemStack dropped = is.copy();
>       float r = rand.nextFloat();
>       List ik = Arrays.asList(new Object[]{is.getItem(), Integer.valueOf(is.getItemDamage())});
>       if(specialMiningResult.containsKey(ik) && r <= chance * ((Float)specialMiningChance.get(ik)).floatValue()) {
>          dropped = ((ItemStack)specialMiningResult.get(ik)).copy();
>          dropped.stackSize *= is.stackSize;
>       }
> 
>       return dropped;
>    }
> ```
> 
> I think you can add your Raw Copper ore item to this registry.
> 
> Also yes, Azanor loves using THREE spaces instead of Tabs...

I don't need to though because it already recognizes my copper ore so it's clearly meeting a check that the deepslate ore is not, despite the raw ore item regular copper and deepslate copper all having the "oreCopper" tag. How would registering the raw ore item solve this?

**Comment by Roadhog360** [comment] 2022-08-14 16:07
Closing this as it has gone 25 days without any further information.

**Closed by Roadhog360** 2022-08-14 16:07 UTC
Labels: Question, Cannot Reproduce
