### ISSUE TITLE
Not a crash, but a possible bug with the composter

### ISSUE THREAD

**Issue by RaidhoSketch** [Roadhog360/Et-Futurum-Requiem#443] opened 2024-03-24 19:16 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.5.1+nomixin

### Describe the Issue

When attempting to press buttons in NEICustomDiagram's Ender Chest handler, prints out a red chat line about being unable to load a recipe. This is, somewhat hilariously, fixed by disabling the composter. So bizarre.

### Conflicting Mods

EnderStorage-1.5.0.jar
NEICustomDiagram-1.5.15.jar
Et_Futurum_Requiem-2.5.1+nomixin.jar

**Comment by Roadhog360** [comment] 2024-03-25 00:31
Please send the exact log errors.

**Comment by RaidhoSketch** [comment] 2024-03-25 06:51
[08:50:36] [ForkJoinPool-1-worker-0/ERROR] [NotEnoughItems/]: Error while looking up usage recipe
[08:50:36] [ForkJoinPool-1-worker-0/ERROR] [NotEnoughItems/]: inputId: neicustomdiagram.diagramgroup.enderstorage.chestoverview-personal
[08:50:36] [ForkJoinPool-1-worker-0/ERROR] [NotEnoughItems/]: ingredients: []
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ArrayIndexOutOfBoundsException: 0
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at ganymedes01.etfuturum.compat.nei.ComposterHandler.loadUsageRecipes(ComposterHandler.java:149)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:611)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiUsageRecipe.getUsageOrCatalystHandler(GuiUsageRecipe.java:81)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.GuiUsageRecipe.lambda$getUsageHandlers$1(GuiUsageRecipe.java:48)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.recipe.RecipeHandlerQuery.lambda$null$3(RecipeHandlerQuery.java:81)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.stream.AbstractTask.compute(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[08:50:36] [ForkJoinPool-1-worker-0/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by makamys** [comment] 2024-03-25 21:31
Looks like a duplicate of #379 which should be fixed already in the dev builds.

**Comment by Roadhog360** [comment] 2024-04-02 03:21
But that's a crash and this isn't.

> Looks like a duplicate of #379 which should be fixed already in the dev builds.

**Comment by makamys** [comment] 2024-04-02 06:53
I'm guessing that's because this user is using GTNH's NEI fork, which catches exceptions, while the previous one used upstream which doesn't.

**Closed** 2024-04-17 18:03 UTC
