### ISSUE TITLE
Hurt sound not plays on server

### ISSUE THREAD

**Issue by iocmet** [Roadhog360/Et-Futurum-Requiem#373] opened 2023-10-27 08:22 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.6.0 (also 2.5.1)

### Describe the issue (IMPORTANT)
There is no hurt sound on server

### Mod list (OPTIONAL)
No other mods, crucible server and et futurm

**Comment by Roadhog360** [comment] 2023-10-27 19:00
How often does this happen? Do you have any reliable steps to reproduce the issue?

**Comment by GregoriusT** [comment] 2023-10-27 23:29
Wait is this the Issue of not being able to connect to the internet to download the new vanilla sounds from mojang?

**Comment by Roadhog360** [comment] 2023-10-28 00:19
Will investigate, thanks.

**Comment by Roadhog360** [comment] 2023-10-28 06:46
Can you provide logs from your client? I can't reproduce this issue

**Comment by Roadhog360** [comment] 2023-10-28 07:01
Misclick

**Comment by Roadhog360** [comment] 2023-10-29 09:18
The time spent in the server seems rather short. Did you actually reproduce the issue in this log? I need a log where you reproduced the issue at least once.

**Comment by Roadhog360** [comment] 2023-10-29 22:42
I still cannot reproduce this after trying again with Dynamic Surroundings installed.

**Comment by Roadhog360** [comment] 2023-10-29 22:44
I also forgot to mention that TLauncher is very shady, and could be the cause of AssetDirector failing. It's not supported because it messes with assets in a way that it shouldn't, and additionally has been found to contain potentially malicious code.

Please tell me if using another launcher fixes the issue.

**Comment by Roadhog360** [comment] 2023-10-30 00:05
Regardless, what happens if you choose a different launcher? (MultiMC, a fork of MultiMC or vanilla launcher)

**Comment by Roadhog360** [comment] 2023-10-30 04:29
That would require me to set up a server, a profile and log in with my two accounts, to test in prod, something I am not in the mood to do. It's a monumental effort for something which an unsupported launcher derives from.
I requested you to try a different launcher because you already have the server, and I want to see if TLauncher Legacy has the same issues that TLauncher does

Upon further inspection, TL Legacy is a **CRACKED LAUNCHER** which is another thing I don't support since cracked launchers always have a tendancy to mess with assets in a weird way, with downloads no longer available to boot. Does it even support Linux, which would be required for me to run it? Yeah no, I can't support this launcher due to it being a cracked launcher, sorry. Those tend to always mess with the game in some bizarre and invasive ways for whatever reason.

**Comment by Roadhog360** [comment] 2023-10-30 04:37
I apologize for the sudden turn of events, but I was under the impression that TLauncher was a cracked fork of TL Legacy, whereas I had been under the impression TL Legacy was a legit and legal launcher. I edited my message a few times out of a panic, so I'm just sending this second message to let you know I'm done editing the above message.

**Comment by Roadhog360** [comment] 2023-10-30 07:31
Bukkit+Forge forks are unsupported due to invasive game-breaking changes, and generally breaking Forge events and API in an unfixable way, also breaks some obscure game mechanics

**Comment by Roadhog360** [comment] 2023-10-30 07:33
This issue is likely unfixable since it's probably being caused by Crucible.
`B:newHurtSounds=false` in `mixins.cfg` will likely be the only way to return hurt sounds to your server.

**Comment by Roadhog360** [comment] 2023-11-02 20:59
Did turning off that option allow hit sounds to work again? If you turn it off, the code responsible for this bug should be entirely turned off but I don't want to assume things.

**Comment by Roadhog360** [comment] 2023-11-05 16:12
I will assume that disabling the conflicting option will allow hit sounds to play in the Crucible server.
Untested due to not receiving a reply, but closing due to the use of unsupported environments

**Closed by Roadhog360** 2023-11-05 16:12 UTC
Labels: Cannot Reproduce

**Comment by VadimFlex** [comment] 2024-01-18 16:37
I don't understand anything about modding, but I'll ask you a question anyway. What is the problem with adding these sounds to the content of the mod? Why download them from the Internet? Does this problem have something to do with licensing? If so, why doesn't this problem occur with block textures and mobs?(as I understand it, they are exactly the same as in vanilla)

**Comment by makamys** [comment] 2024-01-18 17:16
The main motivation was to reduce jar size. The mod jar used to be over 90 MB before it stopped shipping sounds. Textures take up a tiny amount of space in comparison (and they often have to be edited anyway to better fit with the 1.7 textures).

**Comment by VadimFlex** [comment] 2024-01-18 17:55
> The main motivation was to reduce jar size. The mod jar used to be over 90 MB before it stopped shipping sounds. Textures take up a tiny amount of space in comparison (and they often have to be edited anyway to better fit with the 1.7 textures).

Hmm, 90 MB is a lot for a jar file, but in this case, is the file size critical?
