### ISSUE TITLE
Boats & unloaded chunks

### ISSUE THREAD

**Issue by avescarelo** [Roadhog360/Et-Futurum-Requiem#404] opened 2023-12-27 15:06 UTC
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

Et_Futurum_Requiem-2.5.1

### Describe the Issue

I was driving along an ice track, accelerated a lot, ended up in an area of unloaded chunks, hung in the void, re-entered the world and found myself much further than the track...

A - start
B - unloaded chunks
C - founded place

![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/fa497bca-270b-4f8e-9553-112de015afab)

**Comment by avescarelo** [comment] 2023-12-27 15:11
![image](https://github.com/Roadhog360/Et-Futurum-Requiem/assets/26678843/a85fbb81-fdd2-4ca9-bf46-35b79efa892a)
It's looks like teleportation, just entered in non-loaded place and moved

**Comment by GregoriusT** [comment] 2023-12-27 15:30
Correct me if I am wrong, but does that not happen with vanilla Boats in 1.7.10 too, even without Ice Track?

**Comment by Roadhog360** [comment] 2023-12-27 19:53
Please provide a copy of your instance, including mods, configs, a copy of this world, and where this road is in your world.

**Comment by Roadhog360** [comment] 2023-12-28 06:56
I just made a 10,000 block long tunnel and rowed about 5,000 blocks without being able to reproduce this issue. I would occasionally fall through the ground slightly but never teleported far away like you describe.

**Comment by SilearFlare** [comment] 2023-12-28 07:33
Isn't this a known vanilla issue? You load chunks faster than you can render them and the game ends up spazzing out as a result after a while, it is exacerbated by both high speed and high worldgen lag due to terrain generation mods, or amplified terrain. I've had it happen once by cranking smart moving's speed enhancer up to 11, going ludicrously fast while flying and ended needing to relog my save. I ended up diagonally teleported as in the picture.

**Comment by Roadhog360** [comment] 2023-12-28 07:39
If it is, I'm not aware of it. I know sometimes chunk loading gets stuck and requires a relog, but I'm unaware of any glitches that teleport the player far away.
Also I clicked that button 40 minutes ago, why did it just now add the label.

**Comment by avescarelo** [comment] 2023-12-28 23:57
> Isn't this a known vanilla issue? You load chunks faster than you can render them and the game ends up spazzing out as a result after a while, it is exacerbated by both high speed and high worldgen lag due to terrain generation mods, or amplified terrain. I've had it happen once by cranking smart moving's speed enhancer up to 11, going ludicrously fast while flying and ended needing to relog my save. I ended up diagonally teleported as in the picture.

After checking, I have to agree with you
Also, do you know how to fix this vanilla bug?

**Comment by SilearFlare** [comment] 2023-12-29 07:57
Sure
Beefier computer, less/ less intensive worldgen mods, lower render distance, less speed and a bunch of optimization mods in general should do the trick.
I think the issue could mostly be fixed by adding optifine along with coretweaks, it improved my chunk speedup times considerably when playing with capped FPS and I haven't had that issue since. 
Here's a comprehensive list of optimization mods to get you up to speed
https://gist.github.com/makamys/7cb74cd71d93a4332d2891db2624e17c

**Comment by Roadhog360** [comment] 2023-12-29 07:58
I would recommend against OptiFine, instead mods like Neodymium and ArchaicFix, or the alphas of Angelica if it works in your setup.

**Comment by Roadhog360** [comment] 2023-12-29 08:13
I would recommend against using OptiFine and recommend instead to try if the experimental Angelica builds work for you, or trying a combination of mods like Neodymium, BugTorch and ArchaicFix.

**Comment by Roadhog360** [comment] 2023-12-29 08:15
Also since the community consensus is that this is a vanilla issue, this post will be closed

**Closed** 2023-12-29 08:14 UTC
Labels: Invalid
