### ISSUE TITLE
[Suggestion] Add Thaumcraft aspects to items 

### ISSUE THREAD

**Issue by Smokedeuch** [Roadhog360/Et-Futurum-Requiem#215] opened 2023-01-14 20:05 UTC
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [* ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [ ] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> 2.3.1

### Describe the issue (IMPORTANT)
> Use a Thaumcraft scanner to scan any Et-Futurum-Requiem item and block and it will give no Thaumcraft aspects

I believe you can find a legacy of the Thaumcraft 4 API around here https://github.com/Azanor/thaumcraft-api

**Comment by Roadhog360** [comment] 2023-01-14 20:55
Duplicate of #213

**Closed by Roadhog360** 2023-01-14 20:55 UTC

**Comment by makamys** [comment] 2023-01-14 20:58
Duplicate of #213.

**Comment by Roadhog360** [comment] 2023-01-14 21:01
> Duplicate of #213.

Duplicate of https://github.com/Roadhog360/Et-Futurum-Requiem/issues/215#issuecomment-1382915665
